In [ ]:
import pandas as pd
from pathlib import Path
from scipy.stats import zscore
import seaborn as sns
import matplotlib.pyplot as plt
import plotly as py
import plotly.express as px
from plotly.subplots import make_subplots
import plotly.graph_objects as go


players_df = pd.read_csv("../data/processed/fpl/ENG-Premier League/2026-2027/season/cleaned_players.csv", usecols=["name", "fpl_pos", "team", "now_cost", "defcon"])
players_defcon_df = pd.read_csv("../data/processed/fpl/ENG-Premier League/2025-2026/season/cleaned_players.csv", usecols=["player_id", "name", "minutes", "fpl_pos", "team", "now_cost", "defcon", 'total_points', 'goals_scored', 'assists', 'clean_sheets', 'goals_conceded', 'penalties_saved', 'penalties_missed', 'yellow_cards', 'red_cards', 'saves', 'bonus', 'bps', 'xg', 'xa'])
shooting_df = pd.read_csv("../data/processed/whoscored/ENG-Premier League/2025-2026/player_season/shooting.csv", usecols=["player_id", "shots_total", "shots_on_target"])
defense_df = pd.read_csv("../data/processed/whoscored/ENG-Premier League/2025-2026/player_season/defense.csv", usecols=["player_id", "tackles_won", "interceptions", "clearances", "blocks", "recoveries"])
passing_df = pd.read_csv("../data/processed/whoscored/ENG-Premier League/2025-2026/player_season/passing.csv", usecols=["player_id", "key_passes", "big_chances_created"])
weekly_df = pd.read_csv("../data/processed/fpl/ENG-Premier League/2025-2026/gws/merged_gws.csv")

#team data
xg_df = pd.read_csv("../data/processed/understat/ENG-Premier League/2025-2026/team_season.csv", usecols=["team", "team_id", "xg", "np_xg", "xga", "np_xga"])
xg_def_df = pd.read_csv("../data/processed/understat/ENG-Premier League/2025-2026/team_season.csv", usecols=["team", "team_id", "xga", "np_xga"])
elo_df = pd.read_csv("../data/processed/clubelo/ENG-Premier League/2026-2027/schedule.csv", usecols=['team', 'team_id', 'elo_preseason'])
team_shooting = pd.read_csv("../data/processed/whoscored/ENG-Premier League/2025-2026/team_season/shooting.csv", usecols=['team_id', 'shots_total', 'shots_on_target', 'big_chance_shots', 'matches_covered'])
team_passing = pd.read_csv("../data/processed/whoscored/ENG-Premier League/2025-2026/team_season/passing.csv", usecols=['team_id', 'key_passes', 'big_chances_created', 'shot_creating_actions','goal_creating_actions'])
team_poss = pd.read_csv("../data/processed/whoscored/ENG-Premier League/2025-2026/team_season/possession.csv", usecols=['team_id', 'box_entries', 'touches_penalty_area'])
team_defending = pd.read_csv("../data/processed/whoscored/ENG-Premier League/2025-2026/team_season/defending.csv", usecols=["team_id", 'big_chances_conceded', 'box_entries_against', 'shots_conceded', 'shots_on_target_against'])



players_shooting_df = pd.merge(players_defcon_df, shooting_df, how="left", on="player_id")
players_shooting_df = players_shooting_df.fillna(0)

players_defense_df = pd.merge(players_defcon_df, defense_df, how="left", on="player_id")
players_defense_df = players_defense_df.fillna(0)


players_passing_df = pd.merge(players_defcon_df, passing_df, how="left", on="player_id")
players_passing_df = players_passing_df.fillna(0)

team_attack_df = pd.merge(xg_df, team_shooting, how="left", on="team_id")
team_attack_df = pd.merge(team_attack_df, team_passing, how="left", on="team_id")
team_attack_df = pd.merge(team_attack_df, team_poss, how="left", on="team_id")


team_def_df = pd.merge(xg_def_df, team_defending, how='left', on='team_id')

print(team_attack_df.columns)
pd.set_option("display.max_columns", None)
#pd.set_option('display.max_rows', None)

print(players_shooting_df.dtypes)
#print(players_defcon_df.dtypes)
#print(players_defcon_df[players_defcon_df['penalties_missed'] > 0].head())

Index(['team', 'team_id', 'xg', 'xga', 'np_xg', 'np_xga', 'matches_covered',
       'shots_total', 'shots_on_target', 'big_chance_shots', 'key_passes',
       'big_chances_created', 'shot_creating_actions', 'goal_creating_actions',
       'touches_penalty_area', 'box_entries'],
      dtype='str')
goals_scored          int64
assists               int64
total_points          int64
minutes               int64
goals_conceded        int64
bonus                 int64
bps                   int64
clean_sheets          int64
red_cards             int64
yellow_cards          int64
now_cost              int64
name                    str
player_id               str
team                    str
fpl_pos                 str
defcon              float64
xg                  float64
xa                  float64
saves               float64
penalties_saved     float64
penalties_missed    float64
shots_total         float64
shots_on_target     float64
dtype: object

In [279]:
#player prices
def compute_player_price_categories(df, position):
    pos_df = df[df['fpl_pos'] == position].sort_values("now_cost", ascending=False).reset_index(drop=True)
    if position == 'MID':
        edges = [0, 50, 60, 75, 90, 200]
        labels = ['fodder', 'budget', 'mid-tier', 'top-tier', 'premium']
    elif position == 'DEF':
        edges = [0, 45, 55, 65, 75, 200]
        labels = ['fodder', 'budget', 'mid-tier', 'top-tier', 'premium']
    elif position == 'FWD':
        edges = [0, 50, 60, 70, 90, 200]
        labels = ['fodder', 'budget', 'mid-tier', 'top-tier', 'premium']
    elif position == 'GKP':
        edges = [0, 41, 50, 55, 200]
        labels = ['fodder', 'budget', 'mid-tier', 'premium']
    else:
        raise ValueError("Invalid position. Must be one of: MID, DEF, FWD, GKP.")

    categories = pd.cut(pos_df['now_cost'], bins=edges, labels=labels, right=False)
    pos_df['price_category'] = categories
    return pos_df

cols = ['name', 'team', 'fpl_pos', 'now_cost', 'price_category']

for pos, label in [('MID', 'Midfielders'), ('DEF', 'Defenders'), ('FWD', 'Forwards')]:
    pos_df = compute_player_price_categories(players_df, pos)
    print(f"{label} by custom categories:", pos_df['price_category'].value_counts())
    #display(f"{label} Prices:", pos_df[cols])

Midfielders by custom categories: price_category
budget      159
mid-tier     59
fodder       25
top-tier     10
premium       3
Name: count, dtype: int64
Defenders by custom categories: price_category
budget      109
fodder       47
mid-tier     28
top-tier      3
premium       1
Name: count, dtype: int64
Forwards by custom categories: price_category
budget      30
mid-tier    17
fodder      12
top-tier     8
premium      2
Name: count, dtype: int64

In [280]:
#players_df = pd.concat([mids_df, defs_df, fwds_df, gks_df], ignore_index=True)
#display(f"All Players Prices:",  players_df.sort_values("now_cost", ascending=False).reset_index(drop=True))

In [281]:
#players 90s and points/90
#mids
mids_df = players_defcon_df[players_defcon_df['fpl_pos'].eq('MID')].sort_values("defcon", ascending=False).reset_index(drop=True)
mids_df = mids_df[mids_df['minutes'] > 900]

#per 90s calculations
mids_df['90s'] = mids_df['minutes'] / 90
mids_df['ppg'] = mids_df['total_points'] / mids_df['90s']
mids_df['ppg'] = mids_df['ppg'].round(2)
mids_df['goals_per_90'] = mids_df['goals_scored'] / mids_df['90s']
mids_df['assists_per_90'] = mids_df['assists'] / mids_df['90s']
mids_df['defcon_90s'] = mids_df['defcon'] / mids_df['90s']
mids_df['cs_90s'] = mids_df['clean_sheets'] / mids_df['90s']
mids_df['yc_90s'] = mids_df['yellow_cards'] / mids_df['90s']
mids_df['rc_90s'] = mids_df['red_cards'] / mids_df['90s']


#points calculations
mids_df['gPts'] = mids_df['goals_per_90'] * 5
mids_df['aPts'] = mids_df['assists_per_90'] * 3
mids_df['dcPts'] = (mids_df['defcon_90s'] / 12) * 2
mids_df['csPts'] = mids_df['cs_90s'] * 1
mids_df['ycPts'] = mids_df['yc_90s'] * -1
mids_df['rcPts'] = mids_df['rc_90s'] * -3




min_pts = mids_df['ppg'].min()
max_pts = mids_df['ppg'].max()
#display(f"Midfielders points/90:",  mids_df.sort_values("goals_per_90", ascending=False).reset_index(drop=True))
print(f"Midfielders - Min points/90: {min_pts}, Max points/90: {max_pts}")

#defs
defs_df = players_defcon_df[players_defcon_df['fpl_pos'].eq('DEF')].sort_values("defcon", ascending=False).reset_index(drop=True)
defs_df = defs_df[defs_df['minutes'] > 900]
defs_df['90s'] = defs_df['minutes'] / 90
defs_df['ppg'] = defs_df['total_points'] / defs_df['90s']
defs_df['ppg'] = defs_df['ppg'].round(2)
defs_df['goals_per_90'] = defs_df['goals_scored'] / defs_df['90s']
defs_df['assists_per_90'] = defs_df['assists'] / defs_df['90s']
defs_df['defcon_90s'] = defs_df['defcon'] / defs_df['90s']
defs_df['cs_90s'] = defs_df['clean_sheets'] / defs_df['90s']
defs_df['gc_90s'] = defs_df['goals_conceded'] / defs_df['90s']
defs_df['yc_90s'] = defs_df['yellow_cards'] / defs_df['90s']
defs_df['rc_90s'] = defs_df['red_cards'] / defs_df['90s']
min_pts = defs_df['ppg'].min()
max_pts = defs_df['ppg'].max()
#display(f"Defenders points/90:",  defs_df.sort_values("ppg", ascending=False).reset_index(drop=True))
print(f"Defenders - Min points/90: {min_pts}, Max points/90: {max_pts}")

#fwds
fwds_df = players_defcon_df[players_defcon_df['fpl_pos'].eq('FWD')].sort_values("defcon", ascending=False).reset_index(drop=True)
fwds_df = fwds_df[fwds_df['minutes'] > 900]
fwds_df['90s'] = fwds_df['minutes'] / 90
fwds_df['ppg'] = fwds_df['total_points'] / fwds_df['90s']
fwds_df['ppg'] = fwds_df['ppg'].round(2)
fwds_df['goals_per_90'] = fwds_df['goals_scored'] / fwds_df['90s']
fwds_df['assists_per_90'] = fwds_df['assists'] / fwds_df['90s']
fwds_df['defcon_90s'] = fwds_df['defcon'] / fwds_df['90s']
fwds_df['yc_90s'] = fwds_df['yellow_cards'] / fwds_df['90s']
fwds_df['rc_90s'] = fwds_df['red_cards'] / fwds_df['90s']
min_pts = fwds_df['ppg'].min()
max_pts = fwds_df['ppg'].max()  
#display(f"Forwards points/90:",  fwds_df.sort_values("ppg", ascending=False).reset_index(drop=True))
print(f"Forwards - Min points/90: {min_pts}, Max points/90: {max_pts}")

#gks
gks_df = players_defcon_df[players_defcon_df['fpl_pos'].eq('GKP')].sort_values("defcon", ascending=False).reset_index(drop=True)
gks_df = gks_df[gks_df['minutes'] > 900]
gks_df['90s'] = gks_df['minutes'] / 90
gks_df['ppg'] = gks_df['total_points'] / gks_df['90s']
gks_df['ppg'] = gks_df['ppg'].round(2)
gks_df['saves_per_90'] = gks_df['saves'] / gks_df['90s']
gks_df['gc_per_90'] = gks_df['goals_conceded'] / gks_df['90s']
min_pts = gks_df['ppg'].min()
max_pts = gks_df['ppg'].max()
#display(f"Goalkeepers points/90:",  gks_df.sort_values("ppg", ascending=False).reset_index(drop=True))
print(f"Goalkeepers - Min points/90: {min_pts}, Max points/90: {max_pts}")

Midfielders - Min points/90: 2.49, Max points/90: 6.9
Defenders - Min points/90: 1.5, Max points/90: 6.84
Forwards - Min points/90: 2.83, Max points/90: 7.28
Goalkeepers - Min points/90: 1.75, Max points/90: 4.38

In [282]:
#scoring metrics per 90s
def compute_90s(df, columns, mins):
    df = df.copy()
    df = df[df['minutes'] >= mins]
    df = df[df["fpl_pos"].isin(['MID', 'DEF', 'FWD'])]
    df['90s'] = df['minutes'] / 90
    df['reliability'] = df['minutes'] / (df['minutes'].max())
    per_90s = df[columns].div(df['90s'], axis=0)
    per_90s.columns = [f"{col}_p90" for col in columns]
    return pd.concat([df[['name', 'team', 'fpl_pos', 'now_cost', '90s', 'reliability']], per_90s], axis=1)


scoring_cols = ['goals_scored', 'assists', 'xg', 'xa', 'shots_total', 'shots_on_target']
defense_cols = ['tackles_won', 'interceptions', 'clearances', 'blocks', 'recoveries']
cols = ['name', 'team', 'fpl_pos', '90s', 'reliability', 'now_cost'] + [f"{col}_p90" for col in scoring_cols] + [f"{col}_p90" for col in defense_cols]
per_90s = compute_90s(players_shooting_df, scoring_cols, 900)



#scoring metrics z-scores
def compute_z_scores(df, columns):
    df = df.copy()
    df['gls_performance'] = df['goals_scored_p90'] - df['xg_p90']
    z_scores = df[columns].apply(
        lambda column: zscore(column, nan_policy='omit')
    )
    z_scores.columns = [f"{col}_z" for col in columns]
    return pd.concat([df[['name', 'team', 'fpl_pos', 'now_cost', '90s', 'reliability', 'gls_performance']], z_scores], axis=1)



scoring_cols = ["goals_scored_p90", "assists_p90", "xg_p90", "xa_p90", "shots_total_p90", "shots_on_target_p90", "gls_performance"]
cols = ['name', 'team', 'fpl_pos', 'now_cost'] + [f"{col}_z" for col in scoring_cols]
z_scores = compute_z_scores(per_90s, scoring_cols)

def compute_goal_threat_score(df, position):
    pos_df = df.loc[df['fpl_pos'].eq(position)].copy()

    pos_df['goal_threat'] = pos_df['reliability'] * (
        0.45 * pos_df['xg_p90_z']
        + 0.20 * pos_df['shots_total_p90_z']
        + 0.10 * pos_df['shots_on_target_p90_z']
        + 0.25 * pos_df['gls_performance_z']
    ) * 100

    pos_df['goal_threat'] = pos_df['goal_threat'].round(2)
    pos_df['goal_threat_score'] = (
        pos_df['goal_threat'] / pos_df['goal_threat'].max() * 100
    ).round(2)
    pos_df['goal_threat_rank'] = (
        pos_df['goal_threat'].rank(pct=True) * 100
    ).round().astype(int)

    return pos_df

cols = ['name', 'team', '90s', 'reliability', 'fpl_pos', 'now_cost', 'goals_scored_p90_z', 'xg_p90_z', 'shots_on_target_p90_z', 'shots_total_p90_z', 'gls_performance_z',
        'goal_threat', 'goal_threat_score', 'goal_threat_rank']

for pos, label in [('MID', 'Midfielders'), ('DEF', 'Defenders'), ('FWD', 'Forwards')]:
    pos_df = compute_goal_threat_score(z_scores, pos)
    #display(f"{label} Goal threat score:", pos_df[cols].head(200).sort_values("goal_threat", ascending=False).reset_index(drop=True))

In [283]:
#scoring metrics per 90s
def compute_90s(df, columns, mins):
    df = df.copy()
    df = df[df['minutes'] >= mins]
    df = df[df["fpl_pos"].isin(['MID', 'DEF', 'FWD'])]
    df['90s'] = df['minutes'] / 90
    df['reliability'] = df['minutes'] / (df['minutes'].max())
    per_90s = df[columns].div(df['90s'], axis=0)
    per_90s.columns = [f"{col}_p90" for col in columns]
    return pd.concat([df[['name', 'team', 'fpl_pos', 'now_cost', '90s', 'reliability']], per_90s], axis=1)


scoring_cols = ['goals_scored', 'assists', 'xg', 'xa', 'shots_total', 'shots_on_target']
defense_cols = ['tackles_won', 'interceptions', 'clearances', 'blocks', 'recoveries']
cols = ['name', 'team', 'fpl_pos', '90s', 'reliability', 'now_cost'] + [f"{col}_p90" for col in scoring_cols] + [f"{col}_p90" for col in defense_cols]
per_90s = compute_90s(players_shooting_df, scoring_cols, 900)



#scoring metrics z-scores
def compute_z_scores(df, columns):
    df = df.copy()
    df['gls_performance'] = df['goals_scored_p90'] - df['xg_p90']
    z_cols = [f"{col}_z" for col in columns]
    df[z_cols] = (
        df.groupby('fpl_pos')[columns]
        .transform(lambda col: zscore(col, nan_policy='omit'))
    )
    return df[['name', 'team', 'fpl_pos', 'now_cost', '90s', 'reliability', 'gls_performance'] + z_cols]

scoring_cols = ["goals_scored_p90", "assists_p90", "xg_p90", "xa_p90", "shots_total_p90", "shots_on_target_p90", "gls_performance"]
cols = ['name', 'team', 'fpl_pos', 'now_cost'] + [f"{col}_z" for col in scoring_cols]
z_scores = compute_z_scores(per_90s, scoring_cols)

def minmax_score(series):
    spread = series.max() - series.min()

    if spread == 0:
        return pd.Series(50.0, index=series.index)

    return ((series - series.min()) / spread * 100).round(2)

def compute_goal_threat_score(df, position):
    pos_df = df.loc[df['fpl_pos'].eq(position)].copy()

    pos_df['goal_threat'] = pos_df['reliability'] * (
        0.55 * pos_df['xg_p90_z']
        + 0.20 * pos_df['shots_total_p90_z']
        + 0.15 * pos_df['shots_on_target_p90_z']
        + 0.10 * pos_df['gls_performance_z']
    ) * 100

    pos_df['goal_threat'] = pos_df['goal_threat'].round(2)
    pos_df['goal_threat_score'] = minmax_score(pos_df['goal_threat'])
    pos_df['goal_threat_rank'] = (
        pos_df['goal_threat'].rank(pct=True) * 100
    ).round().astype(int)
    pos_df['goal_threat_percentile'] = (
        pos_df['goal_threat']
        .rank(method='average', pct=True)
        .mul(100)
        .round(2)
    )

    return pos_df

cols = ['name', 'team', '90s', 'reliability', 'fpl_pos', 'now_cost', 'goals_scored_p90_z', 'xg_p90_z', 'shots_on_target_p90_z', 'shots_total_p90_z', 'gls_performance_z',
        'goal_threat', 'goal_threat_score', 'goal_threat_rank', 'goal_threat_percentile']

goal_frames = []

for pos, label in [('MID', 'Midfielders'), ('DEF', 'Defenders'), ('FWD', 'Forwards')]:
    pos_df = compute_goal_threat_score(z_scores, pos)
    goal_frames.append(pos_df)
    #display(f"{label} Goal threat score:", pos_df[cols].sort_values("goal_threat_score", ascending=False).reset_index(drop=True))

goals_df = pd.concat(goal_frames, ignore_index=True)

In [284]:
#defensive metrics per 90s
def compute_90s(df, columns, mins):
    df = df.copy()
    df = df[df['minutes'] >= mins]
    df = df[df["fpl_pos"].isin(['MID', 'DEF', 'FWD'])]
    df['90s'] = df['minutes'] / 90
    df['reliability'] = df['minutes'] / (df['minutes'].max())
    per_90s = df[columns].div(df['90s'], axis=0)
    per_90s.columns = [f"{col}_p90" for col in columns]
    return pd.concat([df[['name', 'team', 'fpl_pos', 'now_cost', '90s', 'reliability']], per_90s], axis=1)


defense_cols = ['tackles_won', 'interceptions', 'clearances', 'blocks', 'recoveries']
cols = ['name', 'team', 'fpl_pos', '90s', 'reliability', 'now_cost'] + [f"{col}_p90" for col in defense_cols]
per_90s = compute_90s(players_defense_df, defense_cols, 900)


#z-scores (computed WITHIN each position group via groupby + transform)
def compute_z_scores(df, columns):
    df = df.copy()
    z_cols = [f"{col}_z" for col in columns]
    df[z_cols] = (
        df.groupby('fpl_pos')[columns]
        .transform(lambda col: zscore(col, nan_policy='omit'))
    )
    return df[['name', 'team', 'fpl_pos', 'now_cost', '90s', 'reliability'] + z_cols]


defense_cols_p90 = ['tackles_won_p90', 'interceptions_p90', 'clearances_p90', 'blocks_p90', 'recoveries_p90']
cols = ['name', 'team', 'fpl_pos', 'now_cost'] + [f"{col}_z" for col in defense_cols_p90]
z_scores = compute_z_scores(per_90s, defense_cols_p90)


def compute_defensive_threat_score(df, position):
    pos_df = df.loc[df['fpl_pos'].eq(position)].copy()

    pos_df['defensive_threat'] = pos_df['reliability'] * (
          pos_df['tackles_won_p90_z']
        + pos_df['interceptions_p90_z']
        + pos_df['clearances_p90_z']
        + pos_df['blocks_p90_z']
        + pos_df['recoveries_p90_z']
    ) * 100

    pos_df['defensive_threat'] = pos_df['defensive_threat'].round(2)
    pos_df['defensive_threat_score'] = minmax_score(pos_df['defensive_threat'])
    pos_df['defensive_threat_rank'] = (
        pos_df['defensive_threat'].rank(pct=True) * 100
    ).round(2)

    return pos_df


cols = ['name', 'team', '90s', 'reliability', 'fpl_pos', 'now_cost',
        'tackles_won_p90_z', 'interceptions_p90_z', 'clearances_p90_z', 'blocks_p90_z', 'recoveries_p90_z',
        'defensive_threat', 'defensive_threat_score', 'defensive_threat_rank']

defense_frames = []

for pos, label in [('MID', 'Midfielders'), ('DEF', 'Defenders'), ('FWD', 'Forwards')]:
    pos_df = compute_defensive_threat_score(z_scores, pos)
    defense_frames.append(pos_df)
    #display(f"{label} Defensive threat score:", pos_df[cols].sort_values("defensive_threat", ascending=False).head(200).reset_index(drop=True))

defensive_df = pd.concat(defense_frames, ignore_index=True)

In [285]:
#Creativity metrics per 90s
def compute_90s(df, columns, mins):
    df = df.copy()
    df = df[df['minutes'] >= mins]
    df = df[df["fpl_pos"].isin(['MID', 'DEF', 'FWD'])]
    df['90s'] = df['minutes'] / 90
    df['reliability'] = df['minutes'] / (df['minutes'].max())
    per_90s = df[columns].div(df['90s'], axis=0)
    per_90s.columns = [f"{col}_p90" for col in columns]
    return pd.concat([df[['name', 'team', 'fpl_pos', 'now_cost', '90s', 'reliability']], per_90s], axis=1)



creativity_cols = ['key_passes', 'big_chances_created', 'assists', 'xa']
cols = ['name', 'team', 'fpl_pos', '90s', 'reliability', 'now_cost'] + [f"{col}_p90" for col in creativity_cols]
per_90s = compute_90s(players_passing_df, creativity_cols, 900)


#z-scores
def compute_z_scores(df, columns):
    df = df.copy()
    z_cols = [f'{column}_z' for column in columns]

    df[z_cols] = (
        df.groupby('fpl_pos')[columns]
        .transform(lambda column: zscore(column, nan_policy='omit'))
    )
    return pd.concat([df[['name', 'team', 'fpl_pos', 'now_cost', '90s', 'reliability']], df[z_cols]], axis=1)

creativity_cols = ['key_passes_p90', 'big_chances_created_p90', 'assists_p90', 'xa_p90']
cols = ['name', 'team', 'fpl_pos', 'now_cost'] + [f"{col}_z" for col in creativity_cols]
z_scores = compute_z_scores(per_90s, creativity_cols)

def compute_creativity_score(df, position):
    pos_df = df.loc[df['fpl_pos'].eq(position)].copy()

    pos_df['creativity'] = pos_df['reliability'] * (
        0.25 * pos_df['key_passes_p90_z']
        + 0.15 * pos_df['big_chances_created_p90_z']
        + 0.15 * pos_df['assists_p90_z']
        + 0.45 * pos_df['xa_p90_z']
    ) * 100

    pos_df['creativity'] = pos_df['creativity'].round(2)
    pos_df['creativity_score'] = minmax_score(pos_df['creativity'])
    pos_df['creativity_rank'] = (
        pos_df['creativity'].rank(pct=True) * 100
    ).round().astype(int)

    return pos_df


cols = ['name', 'team', '90s', 'reliability', 'fpl_pos', 'now_cost', 'key_passes_p90_z', 'big_chances_created_p90_z', 'assists_p90_z', 'xa_p90_z',
        'creativity', 'creativity_score', 'creativity_rank']

creative_frames = []

for pos, label in [('MID', 'Midfielders'), ('DEF', 'Defenders'), ('FWD', 'Forwards')]:
    pos_df = compute_creativity_score(z_scores, pos)
    creative_frames.append(pos_df)
    #display(f"{label} Creativity score:", pos_df[cols].sort_values("creativity_score", ascending=False).reset_index(drop=True))

creative_df = pd.concat(creative_frames, ignore_index=True)

In [286]:
print(defense_df.columns.tolist())

['player_id', 'tackles_won', 'blocks', 'interceptions', 'clearances', 'recoveries']

In [287]:
merge_keys = ['name', 'team', 'fpl_pos']

players_scores_df = (
    goals_df[
        merge_keys
        + [
            'goal_threat_score',
            'goal_threat_rank',
        ]
    ]
    .merge(
        defensive_df[
            merge_keys
            + [
                'defensive_threat_score',
                'defensive_threat_rank',
            ]
        ],
        on=merge_keys,
        how='left',
        validate='one_to_one',
    )
    .merge(
        creative_df[
            merge_keys
            + [
                'creativity_score',
                'creativity_rank',
            ]
        ],
        on=merge_keys,
        how='left',
        validate='one_to_one',
    )
)

players_scores_df = players_scores_df.rename(
    columns={
        'goal_threat_rank': 'goal_percentile',
        'defensive_threat_rank': 'defensive_percentile',
        'creativity_rank': 'creativity_percentile',
    }
)

In [288]:
ARCHETYPE_MAP = {
    'FWD': {
        frozenset({'G'}): 'Finisher',
        frozenset({'C'}): 'Creative Forward',
        frozenset({'D'}): 'Pressing Forward',
        frozenset({'G', 'C'}): 'Complete Forward',
        frozenset({'G', 'D'}): 'Pressing Finisher',
        frozenset({'C', 'D'}): 'Pressing Link Forward',
        frozenset({'G', 'C', 'D'}): 'Complete Two-Way Forward',
    },
    'MID': {
        frozenset({'G'}): 'Goal-Scoring Midfielder',
        frozenset({'C'}): 'Playmaker',
        frozenset({'D'}): 'Ball-Winning Midfielder',
        frozenset({'G', 'C'}): 'Attacking Playmaker',
        frozenset({'G', 'D'}): 'Box-to-Box Midfielder',
        frozenset({'C', 'D'}): 'Deep-Lying Playmaker',
        frozenset({'G', 'C', 'D'}): 'Complete Midfielder',
    },
    'DEF': {
        frozenset({'G'}): 'Goal-Threat Defender',
        frozenset({'C'}): 'Creative Defender',
        frozenset({'D'}): 'Defensive Stopper',
        frozenset({'G', 'C'}): 'Attacking Defender',
        frozenset({'G', 'D'}): 'Two-Way Defender',
        frozenset({'C', 'D'}): 'Defensive Creator',
        frozenset({'G', 'C', 'D'}): 'Complete Defender',
    },
}

In [289]:
def assign_production_profile(row):
    scores = {
        'G': row['goal_percentile'],
        'C': row['creativity_percentile'],
        'D': row['defensive_percentile'],
    }

    if any(pd.isna(value) for value in scores.values()):
        return pd.Series({
            'production_archetype': 'Insufficient Data',
            'production_tier': 'Unrated',
            'primary_strength': None,
        })

    primary = max(scores, key=scores.get)
    primary_score = scores[primary]

    # Players below the 40th percentile in everything are genuinely
    # low-production rather than balanced.
    if primary_score < 40:
        archetype = 'Low-Production'
    elif max(scores.values()) - min(scores.values()) <= 10:
        archetype = 'Balanced Profile'
    else:
        traits = {primary}

        for trait, score in scores.items():
            if (
                trait != primary
                and score >= 60
                and primary_score - score <= 15
            ):
                traits.add(trait)

        archetype = ARCHETYPE_MAP[row['fpl_pos']][frozenset(traits)]

    if primary_score >= 90:
        tier = 'Elite'
    elif primary_score >= 75:
        tier = 'High'
    elif primary_score >= 50:
        tier = 'Average'
    else:
        tier = 'Low'

    strength_names = {
        'G': 'Goal Threat',
        'C': 'Creativity',
        'D': 'Defensive Activity',
    }

    return pd.Series({
        'production_archetype': archetype,
        'production_tier': tier,
        'primary_strength': strength_names[primary],
    })

profile_columns = players_scores_df.apply(
    assign_production_profile,
    axis=1,
)

players_scores_df = pd.concat(
    [players_scores_df, profile_columns],
    axis=1,
)

In [290]:
display(
    players_scores_df[
        [
            'name',
            'team',
            'fpl_pos',
            'goal_percentile',
            'creativity_percentile',
            'defensive_percentile',
            'production_archetype',
            'production_tier',
            'primary_strength',
        ]
    ].sort_values(
        ['fpl_pos', 'production_tier', 'goal_percentile'],
        ascending=[True, True, False],
    )
)

,name,team,fpl_pos,goal_percentile,creativity_percentile,defensive_percentile,production_archetype,production_tier,primary_strength
180,Nathan Collins,BRE,DEF,74,61,46.09,Attacking Defender,Average,Goal Threat
251,Morato,NFO,DEF,73,25,58.59,Goal-Threat Defender,Average,Goal Threat
264,Micky van de Ven,TOT,DEF,72,10,6.25,Goal-Threat Defender,Average,Goal Threat
276,Santiago Bueno,WOL,DEF,68,30,17.19,Goal-Threat Defender,Average,Goal Threat
242,Sven Botman,NEW,DEF,67,62,69.53,Balanced Profile,Average,Defensive Activity
...,...,...,...,...,...,...,...,...,...
63,Yéremy Pino,CRY,MID,27,49,39.87,Playmaker,Low,Creativity
24,Lesley Ugochukwu,BUR,MID,23,4,45.75,Ball-Winning Midfielder,Low,Defensive Activity
57,Will Hughes,CRY,MID,20,31,42.48,Ball-Winning Midfielder,Low,Defensive Activity
83,Ilia Gruev,LEE,MID,20,44,37.25,Playmaker,Low,Creativity
67,Idrissa Gana Gueye,EVE,MID,8,9,0.65,Low-Production,Low,Creativity

In [291]:
# merge All scores into one dataframe
players_scores_df = goals_df.copy()

for src_df, score_cols in [
    (defensive_df, ['defensive_threat', 'defensive_threat_score', 'defensive_threat_rank']),
    (creative_df, ['creativity', 'creativity_score', 'creativity_rank']),
]:
    available = [c for c in ['name'] + score_cols if c in src_df.columns]
    players_scores_df = players_scores_df.merge(src_df[available], on='name', how='left')


#Assign archetypes based on goal threat, defensive threat, and creativity ranks
def assign_archetype(row):
    if row['fpl_pos'] == 'FWD':
        if row['goal_threat_score'] >= 70:
            return 'Elite Goal Threat'
        elif row['goal_threat_score'] >= 50 and row['goal_threat_score'] < 70:
            return 'Goal Threat'
        elif row['defensive_threat_score'] >= 65:
            return 'Elite Defensive Threat'
        elif row['defensive_threat_score'] >= 40 and row['defensive_threat_score'] < 65:
            return 'Defensive Threat'
        else:
            return 'Balanced'
        
    if row['fpl_pos'] == 'MID':
            if row['goal_threat_score'] >= 85:
                return 'Elite Goal Threat'
            elif row['goal_threat_score'] >= 70 and row['goal_threat_score'] < 85:
                return 'Goal Threat'
            elif row['defensive_threat_score'] >= 85:
                return 'Elite Defensive Threat'
            elif row['defensive_threat_score'] >= 65 and row['defensive_threat_score'] < 85:
                return 'Defensive Threat'        
            else:
                return 'Balanced'

    if row['fpl_pos'] == 'DEF':
                if row['goal_threat_score'] >= 70:
                    return 'Elite Goal Threat'
                elif row['goal_threat_score'] >= 55 and row['goal_threat_score'] < 70:
                    return 'Goal Threat'
                elif row['defensive_threat_score'] >= 80:
                    return 'Elite Defensive Threat'
                elif row['defensive_threat_score'] >= 60 and row['defensive_threat_score'] < 80:
                    return 'Defensive Threat'
                else:
                    return 'Balanced'

    

players_scores_df['archetype'] = players_scores_df.apply(assign_archetype, axis=1)

goal_getter = players_scores_df[players_scores_df['archetype'].eq('Defensive Threat')].sort_values("goal_threat_score", ascending=False).reset_index(drop=True)


#display(goal_getter)

In [292]:
# Reliability-adjusted metric-level shrinkage
#
# A player's per-90 rate is pulled toward the minutes-weighted mean for
# their FPL position. More minutes means less shrinkage:
# adjusted_rate = reliability * player_rate + (1 - reliability) * position_mean

POSITIONS = ['MID', 'DEF', 'FWD']


def _position_zscore(series):
    std = series.std(ddof=0)
    if pd.isna(std) or std == 0:
        return pd.Series(0.0, index=series.index)
    return (series - series.mean()) / std


def prepare_shrunk_metrics(df, metric_cols, mins=900, prior_minutes=900):
    result = df.loc[
        (df['minutes'] >= mins) & df['fpl_pos'].isin(POSITIONS)
    ].copy()

    result['90s'] = result['minutes'] / 90
    result['reliability'] = (
        result['minutes'] / (result['minutes'] + prior_minutes)
    )

    position_90s = result.groupby('fpl_pos')['90s'].transform('sum')

    for metric in metric_cols:
        p90_col = f'{metric}_p90'
        shrunk_col = f'{metric}_p90_shrunk'
        z_col = f'{metric}_p90_z'

        result[p90_col] = result[metric] / result['90s']

        # Aggregate totals / aggregate 90s gives a minutes-weighted prior.
        position_mean = (
            result.groupby('fpl_pos')[metric].transform('sum') / position_90s
        )
        result[shrunk_col] = (
            result['reliability'] * result[p90_col]
            + (1 - result['reliability']) * position_mean
        )
        result[z_col] = (
            result.groupby('fpl_pos')[shrunk_col]
            .transform(_position_zscore)
        )

    return result


def _scale_0_100(series):
    spread = series.max() - series.min()
    if pd.isna(spread) or spread == 0:
        return pd.Series(50.0, index=series.index)
    return (series - series.min()) / spread * 100


def add_position_composite(df, weights, prefix):
    result = df.copy()
    raw_col = f'{prefix}_raw'
    score_col = f'{prefix}_score'
    percentile_col = f'{prefix}_percentile'
    rank_col = f'{prefix}_rank'

    # Reliability has already been applied to each metric; do not multiply again.
    result[raw_col] = sum(
        weight * result[column] for column, weight in weights.items()
    )
    result[score_col] = (
        result.groupby('fpl_pos')[raw_col]
        .transform(_scale_0_100)
        .round(2)
    )
    result[percentile_col] = (
        result.groupby('fpl_pos')[raw_col]
        .rank(method='average', pct=True)
        .mul(100)
        .round(2).astype(int)
    )
    result[rank_col] = (
        result.groupby('fpl_pos')[raw_col]
        .rank(method='min', ascending=False)
        .astype('Int64')
    )
    return result


# Goal threat
goal_metrics = ['goals_scored', 'xg', 'shots_total', 'shots_on_target']
shrunk_goal_scores = prepare_shrunk_metrics(
    players_shooting_df, goal_metrics, mins=900, prior_minutes=900
)
shrunk_goal_scores['gls_performance_shrunk'] = (
    shrunk_goal_scores['goals_scored_p90_shrunk']
    - shrunk_goal_scores['xg_p90_shrunk']
)
shrunk_goal_scores['gls_performance_z'] = (
    shrunk_goal_scores.groupby('fpl_pos')['gls_performance_shrunk']
    .transform(_position_zscore)
)
shrunk_goal_scores = add_position_composite(
    shrunk_goal_scores,
    {
        'xg_p90_z': 0.55,
        'shots_on_target_p90_z': 0.20,
        'shots_total_p90_z': 0.15,
        'gls_performance_z': 0.10,
    },
    'goal_threat',
)


# Defensive activity
defensive_metrics = [
    'tackles_won', 'interceptions', 'clearances', 'blocks', 'recoveries'
]
shrunk_defensive_scores = prepare_shrunk_metrics(
    players_defense_df, defensive_metrics, mins=900, prior_minutes=900
)
shrunk_defensive_scores = add_position_composite(
    shrunk_defensive_scores,
    {
        'tackles_won_p90_z': 0.20,
        'interceptions_p90_z': 0.25,
        'clearances_p90_z': 0.25,
        'blocks_p90_z': 0.15,
        'recoveries_p90_z': 0.15,
    },
    'defensive_threat',
)


# Creativity
creativity_metrics = ['key_passes', 'big_chances_created', 'assists', 'xa']
shrunk_creativity_scores = prepare_shrunk_metrics(
    players_passing_df, creativity_metrics, mins=900, prior_minutes=900
)
shrunk_creativity_scores = add_position_composite(
    shrunk_creativity_scores,
    {
        'key_passes_p90_z': 0.25,
        'big_chances_created_p90_z': 0.20,
        'assists_p90_z': 0.05,
        'xa_p90_z': 0.50,
    },
    'creativity',
)


# Preview the top 10 in each position for each model.
for label, frame, prefix in [
    ('Goal threat', shrunk_goal_scores, 'goal_threat'),
    ('Defensive threat', shrunk_defensive_scores, 'defensive_threat'),
    ('Creativity', shrunk_creativity_scores, 'creativity'),
]:
    preview_cols = [
        'name', 'team', 'fpl_pos', 'minutes', 'reliability',
        f'{prefix}_score', f'{prefix}_percentile', f'{prefix}_rank',
    ]
    preview = (
        frame.sort_values(['fpl_pos', f'{prefix}_rank'])
        .groupby('fpl_pos', group_keys=False)
        .head(10)[preview_cols]
        .reset_index(drop=True)
    )
    #display(f'{label}: reliability-adjusted top 10 by position', preview)

In [293]:
#Players weekly points returned
players_weekly_pts = weekly_df[['name', 'player_id', 'team', 'fpl_pos', 'total_points', 'minutes', 'was_home', 'defensive_contribution', 'goals_scored', 'assists', 'goals_conceded', 'clean_sheets']].copy()


players_weekly_pts['venue'] = players_weekly_pts['was_home'].apply(lambda x: 'Home' if x else 'Away')


# each players home and away points
def compute_home_away_points(df):
    home_away_points = (
        df.groupby(['name', 'team', 'fpl_pos', 'venue'])
        .agg(
            total_points=('total_points', 'sum'),
            games_played=('total_points', 'count'),
            minutes_played=('minutes', 'sum')
        )
        .reset_index()
    )

    home_away_points['points_per_game'] = (
        home_away_points['total_points'] / home_away_points['games_played']
    ).round(2)

    return home_away_points

display(compute_home_away_points(players_weekly_pts).sort_values(['total_points', 'name', 'fpl_pos'], ascending=[False, True, True]).reset_index(drop=True))

,name,team,fpl_pos,venue,total_points,games_played,minutes_played,points_per_game
0,Bruno Fernandes,MUN,MID,Home,124,19,1526,6.53
1,Erling Haaland,MCI,FWD,Home,120,19,1377,6.32
2,Erling Haaland,MCI,FWD,Away,119,19,1576,6.26
3,Bruno Fernandes,MUN,MID,Away,111,19,1539,5.84
4,Casemiro,MUN,MID,Home,107,19,1464,5.63
...,...,...,...,...,...,...,...,...
1727,Ármin Pécsi,LIV,GKP,Home,0,19,0,0.00
1728,İlkay Gündoğan,MCI,MID,Away,0,19,0,0.00
1729,İlkay Gündoğan,MCI,MID,Home,0,19,0,0.00
1730,Łukasz Fabiański,WHU,GKP,Away,0,17,0,0.00
1731,Łukasz Fabiański,WHU,GKP,Home,0,18,0,0.00

In [294]:
#defcon points return leaders
def compute_defcon_returns(df, position):
    if position not in ['MID', 'DEF', 'FWD']:
        return "Enter a valid position"
    
    threshold = 10 if position == 'DEF' else 12
    pos_df = df.loc[df['fpl_pos'].eq(position)].copy()
    
    result = (
        pos_df.groupby(['name', 'team', 'fpl_pos', 'venue'])['defensive_contribution']
        .apply(lambda x: (x > threshold).sum())
        .reset_index(name='defcon_returns')
    )
    return result

for pos, label in [('MID', 'Midfielders'), ('DEF', 'Defenders'), ('FWD', 'Forwards')]:
    pos_df = compute_defcon_returns(players_weekly_pts, pos)
    display(f"{label} Defensive contribution score:", pos_df.sort_values(["defcon_returns", "team", "name"], ascending=[False, True, True]).reset_index(drop=True))

'Midfielders Defensive contribution score:'

                name team fpl_pos venue  defcon_returns
0    Elliot Anderson  NFO     MID  Away              13
1       James Garner  EVE     MID  Away              11
2       Ethan Ampadu  LEE     MID  Away              10
3    Elliot Anderson  NFO     MID  Home              10
4        André Gomes  WOL     MID  Away               8
..               ...  ...     ...   ...             ...
787  Tawanda Chirewa  WOL     MID  Home               0
788  Temple Ojinnaka  WOL     MID  Away               0
789  Temple Ojinnaka  WOL     MID  Home               0
790       Tom Edozie  WOL     MID  Away               0
791       Tom Edozie  WOL     MID  Home               0

[792 rows x 5 columns]

'Defenders Defensive contribution score:'

                        name team fpl_pos venue  defcon_returns
0              Marcos Senesi  BOU     DEF  Away              12
1            James Tarkowski  EVE     DEF  Away              11
2              Marcos Senesi  BOU     DEF  Home               9
3    Konstantinos Mavropanos  WHU     DEF  Away               9
4             Nathan Collins  BRE     DEF  Home               8
..                       ...  ...     ...   ...             ...
541               Pedro Lima  WOL     DEF  Home               0
542            Rodrigo Gomes  WOL     DEF  Away               0
543            Rodrigo Gomes  WOL     DEF  Home               0
544          Saheed Olagunju  WOL     DEF  Away               0
545          Saheed Olagunju  WOL     DEF  Home               0

[546 rows x 5 columns]

'Forwards Defensive contribution score:'

               name team fpl_pos venue  defcon_returns
0      Jarrod Bowen  WHU     FWD  Away               3
1            Thiago  BRE     FWD  Away               1
2      Jarrod Bowen  WHU     FWD  Home               1
3       Mateus Mane  WOL     FWD  Home               1
4     Gabriel Jesus  ARS     FWD  Away               0
..              ...  ...     ...   ...             ...
192   Nathan Fraser  WOL     FWD  Home               0
193  Sasa Kalajdzic  WOL     FWD  Away               0
194  Sasa Kalajdzic  WOL     FWD  Home               0
195  Tolu Arokodare  WOL     FWD  Away               0
196  Tolu Arokodare  WOL     FWD  Home               0

[197 rows x 5 columns]

In [295]:
#points return leaders
def compute_points_returns(df, position):
  
    threshold = 3
    pos_df = df.loc[df['fpl_pos'].eq(position)].copy()
    
    result = (
        pos_df.groupby(['name', 'team', 'fpl_pos', 'venue'])['total_points']
        .apply(lambda x: (x > threshold).sum())
        .reset_index(name='points_returns')
    )
    return result

for pos, label in [('MID', 'Midfielders'), ('DEF', 'Defenders'), ('FWD', 'Forwards'), ('GKP', 'Goalkeepers')]:
    pos_df = compute_points_returns(players_weekly_pts, pos)
    display(f"{label} Points contribution score:", pos_df.sort_values(["points_returns", "team", "name"], ascending=[False, True, True]).reset_index(drop=True))

'Midfielders Points contribution score:'

                name team fpl_pos venue  points_returns
0    Bruno Fernandes  MUN     MID  Home              14
1    Elliot Anderson  NFO     MID  Away              13
2       James Garner  EVE     MID  Away              12
3           Casemiro  MUN     MID  Home              12
4    Elliot Anderson  NFO     MID  Home              12
..               ...  ...     ...   ...             ...
787  Tawanda Chirewa  WOL     MID  Away               0
788  Tawanda Chirewa  WOL     MID  Home               0
789  Temple Ojinnaka  WOL     MID  Away               0
790  Temple Ojinnaka  WOL     MID  Home               0
791       Tom Edozie  WOL     MID  Away               0

[792 rows x 5 columns]

'Defenders Points contribution score:'

                  name team fpl_pos venue  points_returns
0    Gabriel Magalhães  ARS     DEF  Home              13
1      Adrien Truffert  BOU     DEF  Home              12
2        Nico O’Reilly  MCI     DEF  Home              12
3        Nordi Mukiele  SUN     DEF  Home              12
4        Marcos Senesi  BOU     DEF  Home              11
..                 ...  ...     ...   ...             ...
541         Pedro Lima  WOL     DEF  Away               0
542         Pedro Lima  WOL     DEF  Home               0
543      Rodrigo Gomes  WOL     DEF  Away               0
544    Saheed Olagunju  WOL     DEF  Away               0
545    Saheed Olagunju  WOL     DEF  Home               0

[546 rows x 5 columns]

'Forwards Points contribution score:'

               name team fpl_pos venue  points_returns
0    Erling Haaland  MCI     FWD  Away              11
1    Erling Haaland  MCI     FWD  Home              11
2       Richarlison  TOT     FWD  Away              10
3      Jarrod Bowen  WHU     FWD  Away              10
4      Jarrod Bowen  WHU     FWD  Home              10
..              ...  ...     ...   ...             ...
192    Leon Chiwome  WOL     FWD  Home               0
193   Nathan Fraser  WOL     FWD  Away               0
194   Nathan Fraser  WOL     FWD  Home               0
195  Sasa Kalajdzic  WOL     FWD  Away               0
196  Sasa Kalajdzic  WOL     FWD  Home               0

[197 rows x 5 columns]

'Goalkeepers Points contribution score:'

                     name team fpl_pos venue  points_returns
0              David Raya  ARS     GKP  Home              11
1    Gianluigi Donnarumma  MCI     GKP  Home              11
2              David Raya  ARS     GKP  Away               8
3             Robin Roefs  SUN     GKP  Home               8
4       Caoimhín Kelleher  BRE     GKP  Home               7
..                    ...  ...     ...   ...             ...
192           Josh Gracey  WOL     GKP  Away               0
193           Josh Gracey  WOL     GKP  Home               0
194         Sam Johnstone  WOL     GKP  Away               0
195         Sam Johnstone  WOL     GKP  Home               0
196              Tom King  WOL     GKP  Home               0

[197 rows x 5 columns]

In [296]:
#goals return leaders
def compute_goals_returns(df, position):
    if position not in ['MID', 'DEF', 'FWD']:
        return "Enter a valid position"

    threshold = 0
    pos_df = df.loc[df['fpl_pos'].eq(position)].copy()
    
    result = (
        pos_df.groupby(['name', 'team', 'fpl_pos', 'venue'])['goals_scored']
        .apply(lambda x: (x > threshold).sum())
        .reset_index(name='goals_returns')
    )
    return result

for pos, label in [('MID', 'Midfielders'), ('DEF', 'Defenders'), ('FWD', 'Forwards')]:
    pos_df = compute_goals_returns(players_weekly_pts, pos)
    display(f"{label} Goals contribution score:", pos_df.sort_values(["goals_returns", "team", "name"], ascending=[False, True, True]).reset_index(drop=True))

'Midfielders Goals contribution score:'

                   name team fpl_pos venue  goals_returns
0          Harry Wilson  FUL     MID  Home              8
1       Bruno Guimarães  NEW     MID  Home              8
2    Morgan Gibbs-White  NFO     MID  Away              8
3              Casemiro  MUN     MID  Home              7
4         Matheus Cunha  MUN     MID  Home              6
..                  ...  ...     ...   ...            ...
787     Tawanda Chirewa  WOL     MID  Away              0
788     Tawanda Chirewa  WOL     MID  Home              0
789     Temple Ojinnaka  WOL     MID  Away              0
790     Temple Ojinnaka  WOL     MID  Home              0
791          Tom Edozie  WOL     MID  Away              0

[792 rows x 5 columns]

'Defenders Goals contribution score:'

                 name team fpl_pos venue  goals_returns
0        Daniel Muñoz  CRY     DEF  Away              4
1     Virgil van Dijk  LIV     DEF  Away              4
2       Michael Keane  EVE     DEF  Home              3
3       Nico O’Reilly  MCI     DEF  Home              3
4    Micky van de Ven  TOT     DEF  Away              3
..                ...  ...     ...   ...            ...
541   Saheed Olagunju  WOL     DEF  Home              0
542        Toti Gomes  WOL     DEF  Away              0
543        Toti Gomes  WOL     DEF  Home              0
544   Yerson Mosquera  WOL     DEF  Away              0
545   Yerson Mosquera  WOL     DEF  Home              0

[546 rows x 5 columns]

'Forwards Goals contribution score:'

                  name team fpl_pos venue  goals_returns
0       Erling Haaland  MCI     FWD  Away             10
1       Erling Haaland  MCI     FWD  Home             10
2               Thiago  BRE     FWD  Home              8
3           João Pedro  CHE     FWD  Home              8
4    Eli Junior Kroupi  BOU     FWD  Home              7
..                 ...  ...     ...   ...            ...
192       Leon Chiwome  WOL     FWD  Home              0
193      Nathan Fraser  WOL     FWD  Away              0
194      Nathan Fraser  WOL     FWD  Home              0
195     Sasa Kalajdzic  WOL     FWD  Away              0
196     Sasa Kalajdzic  WOL     FWD  Home              0

[197 rows x 5 columns]

In [297]:
team_elo = elo_df.copy()

team_elo = elo_df.copy()

result = team_elo.groupby(['team', 'team_id'])['elo_preseason'].mean().round().astype(int).reset_index()

league_elo_mean = result['elo_preseason'].mean()
league_std = result['elo_preseason'].std()
print(f"The average elo in the Premier league is {league_elo_mean}")
print(f"The average std in the Premier league is {league_std}")

#elo z-scores
result['elo_z'] = zscore(result['elo_preseason'])
display(result[['team', 'team_id', 'elo_preseason', 'elo_z']].sort_values('elo_preseason', ascending=False).reset_index(drop=True))

The average elo in the Premier league is 1819.4
The average std in the Premier league is 117.84039160973984

   team       team_id  elo_preseason     elo_z
0   ARS      1dd1f33c           2064  2.129612
1   MCI      b11c2f05           1971  1.319907
2   AVL      bcc4ae28           1921  0.884581
3   MUN      767ff900           1915  0.832342
4   LIV      259f237e           1911  0.797516
5   BOU      56f0abca           1872  0.457962
6   BHA      5dbeea62           1842  0.196767
7   NEW      ddbd77d6           1838  0.161941
8   BRE      8331d109           1837  0.153235
9   CHE      1464d629           1831  0.100995
10  NFO      03a0d347           1822  0.022637
11  FUL      049e06ec           1813 -0.055722
12  CRY      53c995cd           1804 -0.134080
13  EVE      f5ee07af           1803 -0.142787
14  LEE      cd881c68           1797 -0.195026
15  TOT      2d0845b3           1777 -0.369156
16  SUN      b842021f           1736 -0.726123
17  COV  ce4d980327c7           1661 -1.379111
18  IPS      53548284           1640 -1.561948
19  HUL      c882a163           1533 -2.493544

In [312]:
team_attack = team_attack_df.copy()

#display(team_attack.sort_values('xg', ascending=False).reset_index(drop=True))

corr_matrix = team_attack.corr(numeric_only=True, method='spearman')
display(corr_matrix)

#sns.heatmap(corr_matrix, annot=True, cmap='coolwarm', vmin=-1, vmax=1)
#plt.show()

#compute per match 
def compute_per_match(df, columns):
    team_match = df.copy()

    per_match = team_match[columns].div(team_match['matches_covered'], axis=0)
    per_match.columns = [f"{col}_pm" for col in columns]
    return pd.concat([team_match[['team', 'team_id']], per_match], axis=1)

cols = ['xg', 'xga', 'np_xg', 'np_xga', 'shots_total', 'shots_on_target', 'big_chance_shots', 'key_passes',
       'big_chances_created', 'shot_creating_actions', 'goal_creating_actions',
       'touches_penalty_area', 'box_entries']

per_match = compute_per_match(team_attack, cols)
print(per_match.columns)


#compute z-scores
def compute_z(df, columns):
    team_df = df.copy()

    z_scores = team_df[columns].apply(
            lambda column: zscore(column, nan_policy='omit')
        )
    z_scores.columns = [f"{col}_z" for col in columns]

    return pd.concat([team_df[['team']], z_scores], axis=1)

att_cols = ['xg_pm', 'xga_pm', 'np_xg_pm', 'np_xga_pm', 'shots_total_pm', 'shots_on_target_pm', 'big_chance_shots_pm', 'key_passes_pm',
       'big_chances_created_pm', 'shot_creating_actions_pm', 'goal_creating_actions_pm',
       'touches_penalty_area_pm', 'box_entries_pm']

z_scores = compute_z(per_match, att_cols)

print(z_scores.columns)

cols = ['xg_pm_z', 'xga_pm_z', 'np_xg_pm_z', 'np_xga_pm_z',
       'shots_total_pm_z', 'shots_on_target_pm_z', 'big_chance_shots_pm_z',
       'key_passes_pm_z', 'big_chances_created_pm_z',
       'shot_creating_actions_pm_z', 'goal_creating_actions_pm_z',
       'touches_penalty_area_pm_z', 'box_entries_pm_z']
z_scores['attMetric_z'] = z_scores[cols].mean(axis=1)


display(z_scores)

,xg,xga,np_xg,np_xga,matches_covered,shots_total,shots_on_target,big_chance_shots,key_passes,big_chances_created,shot_creating_actions,goal_creating_actions,touches_penalty_area,box_entries
xg,1.000000,-0.729323,0.980451,-0.800000,NaN,0.834148,0.818661,0.961960,0.784801,0.891231,0.784801,0.646573,0.837909,0.801504
xga,-0.729323,1.000000,-0.769925,0.953383,NaN,-0.817601,-0.843492,-0.707346,-0.793830,-0.765526,-0.793830,-0.724192,-0.851448,-0.759398
np_xg,0.980451,-0.769925,1.000000,-0.810526,NaN,0.831892,0.849511,0.957440,0.801355,0.924351,0.801355,0.737003,0.852952,0.806015
np_xga,-0.800000,0.953383,-0.810526,1.000000,NaN,-0.801053,-0.824680,-0.798495,-0.732130,-0.815206,-0.732130,-0.608894,-0.832644,-0.721805
matches_covered,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
shots_total,0.834148,-0.817601,0.831892,-0.801053,NaN,1.000000,0.919082,0.715148,0.974784,0.694277,0.974784,0.744065,0.917983,0.919895
shots_on_target,0.818661,-0.843492,0.849511,-0.824680,NaN,0.919082,1.000000,0.765172,0.896837,0.755932,0.896837,0.817120,0.859616,0.855531
big_chance_shots,0.961960,-0.707346,0.957440,-0.798495,NaN,0.715148,0.765172,1.000000,0.661893,0.950981,0.661893,0.594187,0.759609,0.705086
key_passes,0.784801,-0.793830,0.801355,-0.732130,NaN,0.974784,0.896837,0.661893,1.000000,0.676083,1.000000,0.817874,0.913436,0.943567
big_chances_created,0.891231,-0.765526,0.924351,-0.815206,NaN,0.694277,0.755932,0.950981,0.676083,1.000000,0.676083,0.659751,0.806100,0.731653
shot_creating_actions,0.784801,-0.793830,0.801355,-0.732130,NaN,0.974784,0.896837,0.661893,1.000000,0.676083,1.000000,0.817874,0.913436,0.943567
goal_creating_actions,0.646573,-0.724192,0.737003,-0.608894,NaN,0.744065,0.817120,0.594187,0.817874,0.659751,0.817874,1.000000,0.761780,0.803318
touches_penalty_area,0.837909,-0.851448,0.852952,-0.832644,NaN,0.917983,0.859616,0.759609,0.913436,0.806100,0.913436,0.761780,1.000000,0.948477
box_entries,0.801504,-0.759398,0.806015,-0.721805,NaN,0.919895,0.855531,0.705086,0.943567,0.731653,0.943567,0.803318,0.948477,1.000000

Index(['team', 'team_id', 'xg_pm', 'xga_pm', 'np_xg_pm', 'np_xga_pm',
       'shots_total_pm', 'shots_on_target_pm', 'big_chance_shots_pm',
       'key_passes_pm', 'big_chances_created_pm', 'shot_creating_actions_pm',
       'goal_creating_actions_pm', 'touches_penalty_area_pm',
       'box_entries_pm'],
      dtype='str')
Index(['team', 'xg_pm_z', 'xga_pm_z', 'np_xg_pm_z', 'np_xga_pm_z',
       'shots_total_pm_z', 'shots_on_target_pm_z', 'big_chance_shots_pm_z',
       'key_passes_pm_z', 'big_chances_created_pm_z',
       'shot_creating_actions_pm_z', 'goal_creating_actions_pm_z',
       'touches_penalty_area_pm_z', 'box_entries_pm_z'],
      dtype='str')

,team,xg_pm_z,xga_pm_z,np_xg_pm_z,np_xga_pm_z,shots_total_pm_z,shots_on_target_pm_z,big_chance_shots_pm_z,key_passes_pm_z,big_chances_created_pm_z,shot_creating_actions_pm_z,goal_creating_actions_pm_z,touches_penalty_area_pm_z,box_entries_pm_z,attMetric_z
0,ARS,1.590403,-2.679789,1.716695,-2.584784,1.114971,1.021006,1.460073,0.990256,1.362186,0.990256,1.744592,1.642699,1.167614,0.733552
1,MCI,1.744213,-1.247058,1.878830,-1.178335,1.695833,1.785168,1.660083,1.807134,2.017083,1.807134,2.378989,2.462387,2.294346,1.469677
2,MUN,1.155303,-0.840707,1.126251,-0.887517,1.695833,2.167250,1.210061,1.757121,0.903758,1.757121,1.215927,0.435321,0.808655,0.961875
3,AVL,-0.157417,-0.154155,0.137816,0.066094,0.123256,0.554018,0.010001,0.340088,0.052392,0.340088,0.581531,0.075323,0.240303,0.169949
4,LIV,0.750473,-0.455853,0.963075,-0.455661,1.624996,0.638925,0.660033,1.890488,1.100227,1.890488,1.004462,1.731314,2.084953,1.032917
5,BOU,0.715638,-0.144830,0.662784,-0.289859,0.689951,0.808739,0.160008,0.306746,-0.209567,0.306746,0.052866,-0.063138,-0.078772,0.224409
6,SUN,-1.230495,0.237751,-1.322820,0.414259,-1.123472,-1.186574,-1.090055,-1.260326,-1.060933,-1.260326,-0.898729,-1.115440,-0.976169,-0.913333
7,BHA,0.024595,-0.468571,0.000219,-0.653142,0.279097,0.554018,0.110006,0.290075,0.052392,0.290075,-0.158599,0.601474,0.120650,0.080176
8,BRE,0.668182,0.106170,0.349188,-0.191420,-0.995966,-0.464865,1.410071,-0.876893,1.558655,-0.876893,-0.158599,-0.101907,-0.138598,0.022086
9,CHE,1.157281,-0.000292,0.996551,0.238749,0.463273,0.384204,0.860043,0.556811,0.772778,0.556811,0.475798,0.224860,0.429754,0.547432
10,FUL,-0.701245,0.292110,-0.764920,0.383650,0.109089,-0.846947,-1.190060,0.073352,-1.453871,0.073352,-0.898729,-0.101907,0.230332,-0.368907
11,NEW,0.204735,-0.086674,0.124218,-0.132999,0.250762,0.596471,0.160008,0.106694,-0.013098,0.106694,-0.158599,0.125169,0.320072,0.123343
12,EVE,-0.677496,0.201059,-0.542207,0.281479,-0.755120,-0.677133,-0.740037,-0.560145,-0.667995,-0.560145,-0.052866,-0.362214,-0.427759,-0.426198
13,LEE,0.135539,-0.192436,-0.093489,-0.343283,0.038252,-0.379959,0.160008,-0.360093,-0.144077,-0.360093,-1.110195,-0.367752,-0.597268,-0.278065
14,CRY,0.356105,0.206568,0.151997,0.012844,-0.485941,-0.719586,0.660033,-0.810209,0.445330,-0.810209,-1.215927,-0.340060,-0.667065,-0.247394
15,NFO,-0.754200,0.709934,-0.688955,0.669292,0.009917,0.002123,-0.840042,-0.010003,-0.667995,-0.010003,-0.052866,-0.677904,-0.288164,-0.199913
16,TOT,-0.929940,-0.271261,-0.676533,-0.156919,-0.514275,-0.507319,-0.890045,-0.560145,-0.537016,-0.560145,0.158599,-0.212676,-0.467644,-0.471178
17,WHU,-0.696372,1.072067,-0.627998,0.984049,-1.024300,-0.677133,-0.640032,-0.876893,-0.798974,-0.876893,-0.370065,-1.065595,-1.115764,-0.516454
18,BUR,-1.739247,2.623752,-1.661442,2.633635,-1.704334,-1.696016,-1.540077,-1.393693,-1.257402,-1.393693,-0.792996,-1.719130,-1.724000,-0.874203
19,WOL,-1.616055,1.092214,-1.729259,1.189871,-1.491823,-1.356388,-1.590080,-1.410364,-1.453871,-1.410364,-1.744592,-1.170825,-1.215475,-1.069770

In [317]:
test_df = pd.merge(result, z_scores, how='left', on='team')
test_df = test_df.dropna()


test_df['att_strength'] = (league_elo_mean + 60 * test_df['elo_z'] + 40 * test_df['attMetric_z']).round().astype(int)
display(test_df[['team', 'attMetric_z', 'elo_preseason','att_strength' ]].sort_values(['att_strength'], ascending=False).reset_index(drop=True))

   team  attMetric_z  elo_preseason  att_strength
0   ARS     0.733552           2064          1977
1   MCI     1.469677           1971          1957
2   LIV     1.032917           1911          1909
3   MUN     0.961875           1915          1908
4   AVL     0.169949           1921          1879
5   BOU     0.224409           1872          1856
6   CHE     0.547432           1831          1847
7   NEW     0.123343           1838          1834
8   BHA     0.080176           1842          1834
9   BRE     0.022086           1837          1829
10  NFO    -0.199913           1822          1813
11  CRY    -0.247394           1804          1801
12  FUL    -0.368907           1813          1801
13  LEE    -0.278065           1797          1797
14  EVE    -0.426198           1803          1794
15  TOT    -0.471178           1777          1778
16  SUN    -0.913333           1736          1739