In [32]:
import pandas as pd
import numpy as np
from pathlib import Path
from scipy.stats import zscore
import seaborn as sns
import matplotlib.pyplot as plt
import plotly as py
import plotly.express as px
from plotly.subplots import make_subplots
import plotly.graph_objects as go
from sklearn.linear_model import LinearRegression



players_df = pd.read_csv("../data/processed/fpl/ENG-Premier League/2026-2027/season/cleaned_players.csv", usecols=["name", "fpl_pos", "team", "now_cost", "defcon"])
players_defcon_df = pd.read_csv("../data/processed/fpl/ENG-Premier League/2025-2026/season/cleaned_players.csv", usecols=["player_id", "name", "minutes", "fpl_pos", "team", "now_cost", "defcon", 'total_points', 'goals_scored', 'assists', 'clean_sheets', 'goals_conceded', 'penalties_saved', 'penalties_missed', 'yellow_cards', 'red_cards', 'saves', 'bonus', 'bps', 'xg', 'xa'])
shooting_df = pd.read_csv("../data/processed/whoscored/ENG-Premier League/2025-2026/player_season/shooting.csv", usecols=["player_id", "shots_total", "shots_on_target"])
defense_df = pd.read_csv("../data/processed/whoscored/ENG-Premier League/2025-2026/player_season/defense.csv", usecols=["player_id", "tackles_won", "interceptions", "clearances", "blocks", "recoveries"])
passing_df = pd.read_csv("../data/processed/whoscored/ENG-Premier League/2025-2026/player_season/passing.csv", usecols=["player_id", "key_passes", "big_chances_created"])
weekly_df = pd.read_csv("../data/processed/fpl/ENG-Premier League/2025-2026/gws/merged_gws.csv")

#team data
xg_df = pd.read_csv("../data/processed/understat/ENG-Premier League/2025-2026/team_season.csv", usecols=["team", "team_id", "xg", "np_xg", "xga", "np_xga"])
xg_def_df = pd.read_csv("../data/processed/understat/ENG-Premier League/2025-2026/team_season.csv", usecols=["team", "team_id", "xga", "np_xga"])
elo_df = pd.read_csv("../data/processed/clubelo/ENG-Premier League/2026-2027/schedule.csv", usecols=['team', 'team_id', 'elo_preseason'])
team_shooting = pd.read_csv("../data/processed/whoscored/ENG-Premier League/2025-2026/team_season/shooting.csv", usecols=['team_id', 'shots_total', 'shots_on_target', 'big_chance_shots', 'matches_covered'])
team_passing = pd.read_csv("../data/processed/whoscored/ENG-Premier League/2025-2026/team_season/passing.csv", usecols=['team_id', 'key_passes', 'big_chances_created', 'shot_creating_actions','goal_creating_actions'])
team_poss = pd.read_csv("../data/processed/whoscored/ENG-Premier League/2025-2026/team_season/possession.csv", usecols=['team_id', 'box_entries', 'touches_penalty_area'])
team_defending = pd.read_csv("../data/processed/whoscored/ENG-Premier League/2025-2026/team_season/defense.csv", usecols=["team_id", 'matches_covered', 'big_chances_conceded', 'box_entries_against', 'shots_conceded', 'shots_on_target_against'])



players_shooting_df = pd.merge(players_defcon_df, shooting_df, how="left", on="player_id")
players_shooting_df = players_shooting_df.fillna(0)

players_defense_df = pd.merge(players_defcon_df, defense_df, how="left", on="player_id")
players_defense_df = players_defense_df.fillna(0)


players_passing_df = pd.merge(players_defcon_df, passing_df, how="left", on="player_id")
players_passing_df = players_passing_df.fillna(0)

team_attack_df = pd.merge(xg_df, team_shooting, how="left", on="team_id")
team_attack_df = pd.merge(team_attack_df, team_passing, how="left", on="team_id")
team_attack_df = pd.merge(team_attack_df, team_poss, how="left", on="team_id")


team_def_df = pd.merge(xg_def_df, team_defending, how='left', on='team_id')

print(team_attack_df.columns)
pd.set_option("display.max_columns", None)
#pd.set_option('display.max_rows', None)

print(players_shooting_df.dtypes)
#print(players_defcon_df.dtypes)
#print(players_defcon_df[players_defcon_df['penalties_missed'] > 0].head())

Index(['team', 'team_id', 'xg', 'xga', 'np_xg', 'np_xga', 'matches_covered',
       'shots_total', 'shots_on_target', 'big_chance_shots', 'key_passes',
       'big_chances_created', 'shot_creating_actions', 'goal_creating_actions',
       'touches_penalty_area', 'box_entries'],
      dtype='str')
goals_scored          int64
assists               int64
total_points          int64
minutes               int64
goals_conceded        int64
bonus                 int64
bps                   int64
clean_sheets          int64
red_cards             int64
yellow_cards          int64
now_cost              int64
name                    str
player_id               str
team                    str
fpl_pos                 str
defcon              float64
xg                  float64
xa                  float64
saves               float64
penalties_saved     float64
penalties_missed    float64
shots_total         float64
shots_on_target     float64
dtype: object

In [33]:
#player prices
def compute_player_price_categories(df, position):
    pos_df = df[df['fpl_pos'] == position].sort_values("now_cost", ascending=False).reset_index(drop=True)
    if position == 'MID':
        edges = [0, 50, 60, 75, 90, 200]
        labels = ['fodder', 'budget', 'mid-tier', 'top-tier', 'premium']
    elif position == 'DEF':
        edges = [0, 45, 55, 65, 75, 200]
        labels = ['fodder', 'budget', 'mid-tier', 'top-tier', 'premium']
    elif position == 'FWD':
        edges = [0, 50, 60, 70, 90, 200]
        labels = ['fodder', 'budget', 'mid-tier', 'top-tier', 'premium']
    elif position == 'GKP':
        edges = [0, 41, 50, 55, 200]
        labels = ['fodder', 'budget', 'mid-tier', 'premium']
    else:
        raise ValueError("Invalid position. Must be one of: MID, DEF, FWD, GKP.")

    categories = pd.cut(pos_df['now_cost'], bins=edges, labels=labels, right=False)
    pos_df['price_category'] = categories
    return pos_df

cols = ['name', 'team', 'fpl_pos', 'now_cost', 'price_category']

for pos, label in [('MID', 'Midfielders'), ('DEF', 'Defenders'), ('FWD', 'Forwards')]:
    pos_df = compute_player_price_categories(players_df, pos)
    print(f"{label} by custom categories:", pos_df['price_category'].value_counts())
    #display(f"{label} Prices:", pos_df[cols])

Midfielders by custom categories: price_category
budget      165
mid-tier     59
fodder       25
top-tier     10
premium       3
Name: count, dtype: int64
Defenders by custom categories: price_category
budget      114
fodder       50
mid-tier     30
top-tier      3
premium       1
Name: count, dtype: int64
Forwards by custom categories: price_category
budget      32
mid-tier    18
fodder      12
top-tier     8
premium      2
Name: count, dtype: int64

In [34]:
#players_df = pd.concat([mids_df, defs_df, fwds_df, gks_df], ignore_index=True)
#display(f"All Players Prices:",  players_df.sort_values("now_cost", ascending=False).reset_index(drop=True))

In [35]:
#players 90s and points/90
#mids
mids_df = players_defcon_df[players_defcon_df['fpl_pos'].eq('MID')].sort_values("defcon", ascending=False).reset_index(drop=True)
mids_df = mids_df[mids_df['minutes'] > 450]

#per 90s calculations
mids_df['90s'] = mids_df['minutes'] / 90
mids_df['ppg'] = mids_df['total_points'] / mids_df['90s']
mids_df['ppg'] = mids_df['ppg'].round(2)
mids_df['goals_per_90'] = mids_df['goals_scored'] / mids_df['90s']
mids_df['assists_per_90'] = mids_df['assists'] / mids_df['90s']
mids_df['defcon_90s'] = mids_df['defcon'] / mids_df['90s']
mids_df['cs_90s'] = mids_df['clean_sheets'] / mids_df['90s']
mids_df['yc_90s'] = mids_df['yellow_cards'] / mids_df['90s']
mids_df['rc_90s'] = mids_df['red_cards'] / mids_df['90s']


#points calculations
mids_df['gPts'] = mids_df['goals_per_90'] * 5
mids_df['aPts'] = mids_df['assists_per_90'] * 3
mids_df['dcPts'] = (mids_df['defcon_90s'] / 12) * 2
mids_df['csPts'] = mids_df['cs_90s'] * 1
mids_df['ycPts'] = mids_df['yc_90s'] * -1
mids_df['rcPts'] = mids_df['rc_90s'] * -3




min_pts = mids_df['ppg'].min()
max_pts = mids_df['ppg'].max()
#display(f"Midfielders points/90:",  mids_df.sort_values("goals_per_90", ascending=False).reset_index(drop=True))
print(f"Midfielders - Min points/90: {min_pts}, Max points/90: {max_pts}")

#defs
defs_df = players_defcon_df[players_defcon_df['fpl_pos'].eq('DEF')].sort_values("defcon", ascending=False).reset_index(drop=True)
defs_df = defs_df[defs_df['minutes'] > 450]
defs_df['90s'] = defs_df['minutes'] / 90
defs_df['ppg'] = defs_df['total_points'] / defs_df['90s']
defs_df['ppg'] = defs_df['ppg'].round(2)
defs_df['goals_per_90'] = defs_df['goals_scored'] / defs_df['90s']
defs_df['assists_per_90'] = defs_df['assists'] / defs_df['90s']
defs_df['defcon_90s'] = defs_df['defcon'] / defs_df['90s']
defs_df['cs_90s'] = defs_df['clean_sheets'] / defs_df['90s']
defs_df['gc_90s'] = defs_df['goals_conceded'] / defs_df['90s']
defs_df['yc_90s'] = defs_df['yellow_cards'] / defs_df['90s']
defs_df['rc_90s'] = defs_df['red_cards'] / defs_df['90s']
min_pts = defs_df['ppg'].min()
max_pts = defs_df['ppg'].max()
#display(f"Defenders points/90:",  defs_df.sort_values("ppg", ascending=False).reset_index(drop=True))
print(f"Defenders - Min points/90: {min_pts}, Max points/90: {max_pts}")

#fwds
fwds_df = players_defcon_df[players_defcon_df['fpl_pos'].eq('FWD')].sort_values("defcon", ascending=False).reset_index(drop=True)
fwds_df = fwds_df[fwds_df['minutes'] > 450]
fwds_df['90s'] = fwds_df['minutes'] / 90
fwds_df['ppg'] = fwds_df['total_points'] / fwds_df['90s']
fwds_df['ppg'] = fwds_df['ppg'].round(2)
fwds_df['goals_per_90'] = fwds_df['goals_scored'] / fwds_df['90s']
fwds_df['assists_per_90'] = fwds_df['assists'] / fwds_df['90s']
fwds_df['defcon_90s'] = fwds_df['defcon'] / fwds_df['90s']
fwds_df['yc_90s'] = fwds_df['yellow_cards'] / fwds_df['90s']
fwds_df['rc_90s'] = fwds_df['red_cards'] / fwds_df['90s']
min_pts = fwds_df['ppg'].min()
max_pts = fwds_df['ppg'].max()  
#display(f"Forwards points/90:",  fwds_df.sort_values("ppg", ascending=False).reset_index(drop=True))
print(f"Forwards - Min points/90: {min_pts}, Max points/90: {max_pts}")

#gks
gks_df = players_defcon_df[players_defcon_df['fpl_pos'].eq('GKP')].sort_values("defcon", ascending=False).reset_index(drop=True)
gks_df = gks_df[gks_df['minutes'] > 450]
gks_df['90s'] = gks_df['minutes'] / 90
gks_df['ppg'] = gks_df['total_points'] / gks_df['90s']
gks_df['ppg'] = gks_df['ppg'].round(2)
gks_df['saves_per_90'] = gks_df['saves'] / gks_df['90s']
gks_df['gc_per_90'] = gks_df['goals_conceded'] / gks_df['90s']
min_pts = gks_df['ppg'].min()
max_pts = gks_df['ppg'].max()
#display(f"Goalkeepers points/90:",  gks_df.sort_values("ppg", ascending=False).reset_index(drop=True))
print(f"Goalkeepers - Min points/90: {min_pts}, Max points/90: {max_pts}")

Midfielders - Min points/90: 2.49, Max points/90: 7.73
Defenders - Min points/90: 1.34, Max points/90: 6.84
Forwards - Min points/90: 2.83, Max points/90: 8.5
Goalkeepers - Min points/90: 1.75, Max points/90: 4.38

In [36]:
#scoring metrics per 90s
def compute_90s(df, columns, mins):
    df = df.copy()
    df = df[df['minutes'] >= mins]
    df = df[df["fpl_pos"].isin(['MID', 'DEF', 'FWD'])]
    df['90s'] = df['minutes'] / 90
    df['reliability'] = df['minutes'] / (df['minutes'].max())
    per_90s = df[columns].div(df['90s'], axis=0)
    per_90s.columns = [f"{col}_p90" for col in columns]
    return pd.concat([df[['name', 'team', 'fpl_pos', 'now_cost', '90s', 'reliability']], per_90s], axis=1)


scoring_cols = ['goals_scored', 'assists', 'xg', 'xa', 'shots_total', 'shots_on_target']
defense_cols = ['tackles_won', 'interceptions', 'clearances', 'blocks', 'recoveries']
cols = ['name', 'team', 'fpl_pos', '90s', 'reliability', 'now_cost'] + [f"{col}_p90" for col in scoring_cols] + [f"{col}_p90" for col in defense_cols]
per_90s = compute_90s(players_shooting_df, scoring_cols, 450)



#scoring metrics z-scores
def compute_z_scores(df, columns):
    df = df.copy()
    df['gls_performance'] = df['goals_scored_p90'] - df['xg_p90']
    z_scores = df[columns].apply(
        lambda column: zscore(column, nan_policy='omit')
    )
    z_scores.columns = [f"{col}_z" for col in columns]
    return pd.concat([df[['name', 'team', 'fpl_pos', 'now_cost', '90s', 'reliability', 'gls_performance']], z_scores], axis=1)



scoring_cols = ["goals_scored_p90", "assists_p90", "xg_p90", "xa_p90", "shots_total_p90", "shots_on_target_p90", "gls_performance"]
cols = ['name', 'team', 'fpl_pos', 'now_cost'] + [f"{col}_z" for col in scoring_cols]
z_scores = compute_z_scores(per_90s, scoring_cols)

def compute_goal_threat_score(df, position):
    pos_df = df.loc[df['fpl_pos'].eq(position)].copy()

    pos_df['goal_threat'] = pos_df['reliability'] * (
        0.45 * pos_df['xg_p90_z']
        + 0.20 * pos_df['shots_total_p90_z']
        + 0.10 * pos_df['shots_on_target_p90_z']
        + 0.25 * pos_df['gls_performance_z']
    ) * 100

    pos_df['goal_threat'] = pos_df['goal_threat'].round(2)
    pos_df['goal_threat_score'] = (
        pos_df['goal_threat'] / pos_df['goal_threat'].max() * 100
    ).round(2)
    pos_df['goal_threat_rank'] = (
        pos_df['goal_threat'].rank(pct=True) * 100
    ).round().astype(int)

    return pos_df

cols = ['name', 'team', '90s', 'reliability', 'fpl_pos', 'now_cost', 'goals_scored_p90_z', 'xg_p90_z', 'shots_on_target_p90_z', 'shots_total_p90_z', 'gls_performance_z',
        'goal_threat', 'goal_threat_score', 'goal_threat_rank']

for pos, label in [('MID', 'Midfielders'), ('DEF', 'Defenders'), ('FWD', 'Forwards')]:
    pos_df = compute_goal_threat_score(z_scores, pos)
    #display(f"{label} Goal threat score:", pos_df[cols].head(200).sort_values("goal_threat", ascending=False).reset_index(drop=True))

In [37]:
#scoring metrics per 90s
def compute_90s(df, columns, mins):
    df = df.copy()
    df = df[df['minutes'] >= mins]
    df = df[df["fpl_pos"].isin(['MID', 'DEF', 'FWD'])]
    df['90s'] = df['minutes'] / 90
    df['reliability'] = df['minutes'] / (df['minutes'].max())
    per_90s = df[columns].div(df['90s'], axis=0)
    per_90s.columns = [f"{col}_p90" for col in columns]
    return pd.concat([df[['name', 'team', 'fpl_pos', 'now_cost', '90s', 'reliability']], per_90s], axis=1)


scoring_cols = ['goals_scored', 'assists', 'xg', 'xa', 'shots_total', 'shots_on_target']
defense_cols = ['tackles_won', 'interceptions', 'clearances', 'blocks', 'recoveries']
cols = ['name', 'team', 'fpl_pos', '90s', 'reliability', 'now_cost'] + [f"{col}_p90" for col in scoring_cols] + [f"{col}_p90" for col in defense_cols]
per_90s = compute_90s(players_shooting_df, scoring_cols, 450)



#scoring metrics z-scores
def compute_z_scores(df, columns):
    df = df.copy()
    df['gls_performance'] = df['goals_scored_p90'] - df['xg_p90']
    z_cols = [f"{col}_z" for col in columns]
    df[z_cols] = (
        df.groupby('fpl_pos')[columns]
        .transform(lambda col: zscore(col, nan_policy='omit'))
    )
    return df[['name', 'team', 'fpl_pos', 'now_cost', '90s', 'reliability', 'gls_performance'] + z_cols]

scoring_cols = ["goals_scored_p90", "assists_p90", "xg_p90", "xa_p90", "shots_total_p90", "shots_on_target_p90", "gls_performance"]
cols = ['name', 'team', 'fpl_pos', 'now_cost'] + [f"{col}_z" for col in scoring_cols]
z_scores = compute_z_scores(per_90s, scoring_cols)

def minmax_score(series):
    spread = series.max() - series.min()

    if spread == 0:
        return pd.Series(50.0, index=series.index)

    return ((series - series.min()) / spread * 100).round(2)

def compute_goal_threat_score(df, position):
    pos_df = df.loc[df['fpl_pos'].eq(position)].copy()

    pos_df['goal_threat'] = pos_df['reliability'] * (
        0.55 * pos_df['xg_p90_z']
        + 0.20 * pos_df['shots_total_p90_z']
        + 0.15 * pos_df['shots_on_target_p90_z']
        + 0.10 * pos_df['gls_performance_z']
    ) * 100

    pos_df['goal_threat'] = pos_df['goal_threat'].round(2)
    pos_df['goal_threat_score'] = minmax_score(pos_df['goal_threat'])
    pos_df['goal_threat_rank'] = (
        pos_df['goal_threat'].rank(pct=True) * 100
    ).round().astype(int)
    pos_df['goal_threat_percentile'] = (
        pos_df['goal_threat']
        .rank(method='average', pct=True)
        .mul(100)
        .round(2)
    )

    return pos_df

cols = ['name', 'team', '90s', 'reliability', 'fpl_pos', 'now_cost', 'goals_scored_p90_z', 'xg_p90_z', 'shots_on_target_p90_z', 'shots_total_p90_z', 'gls_performance_z',
        'goal_threat', 'goal_threat_score', 'goal_threat_rank', 'goal_threat_percentile']

goal_frames = []

for pos, label in [('MID', 'Midfielders'), ('DEF', 'Defenders'), ('FWD', 'Forwards')]:
    pos_df = compute_goal_threat_score(z_scores, pos)
    goal_frames.append(pos_df)
    #display(f"{label} Goal threat score:", pos_df[cols].sort_values("goal_threat_score", ascending=False).reset_index(drop=True))

goals_df = pd.concat(goal_frames, ignore_index=True)

In [38]:
#defensive metrics per 90s
def compute_90s(df, columns, mins):
    df = df.copy()
    df = df[df['minutes'] >= mins]
    df = df[df["fpl_pos"].isin(['MID', 'DEF', 'FWD'])]
    df['90s'] = df['minutes'] / 90
    df['reliability'] = df['minutes'] / (df['minutes'].max())
    per_90s = df[columns].div(df['90s'], axis=0)
    per_90s.columns = [f"{col}_p90" for col in columns]
    return pd.concat([df[['name', 'team', 'fpl_pos', 'now_cost', '90s', 'reliability']], per_90s], axis=1)


defense_cols = ['tackles_won', 'interceptions', 'clearances', 'blocks', 'recoveries']
cols = ['name', 'team', 'fpl_pos', '90s', 'reliability', 'now_cost'] + [f"{col}_p90" for col in defense_cols]
per_90s = compute_90s(players_defense_df, defense_cols, 450)


#z-scores (computed WITHIN each position group via groupby + transform)
def compute_z_scores(df, columns):
    df = df.copy()
    z_cols = [f"{col}_z" for col in columns]
    df[z_cols] = (
        df.groupby('fpl_pos')[columns]
        .transform(lambda col: zscore(col, nan_policy='omit'))
    )
    return df[['name', 'team', 'fpl_pos', 'now_cost', '90s', 'reliability'] + z_cols]


defense_cols_p90 = ['tackles_won_p90', 'interceptions_p90', 'clearances_p90', 'blocks_p90', 'recoveries_p90']
cols = ['name', 'team', 'fpl_pos', 'now_cost'] + [f"{col}_z" for col in defense_cols_p90]
z_scores = compute_z_scores(per_90s, defense_cols_p90)


def compute_defensive_threat_score(df, position):
    pos_df = df.loc[df['fpl_pos'].eq(position)].copy()

    pos_df['defensive_threat'] = pos_df['reliability'] * (
          pos_df['tackles_won_p90_z']
        + pos_df['interceptions_p90_z']
        + pos_df['clearances_p90_z']
        + pos_df['blocks_p90_z']
        + pos_df['recoveries_p90_z']
    ) * 100

    pos_df['defensive_threat'] = pos_df['defensive_threat'].round(2)
    pos_df['defensive_threat_score'] = minmax_score(pos_df['defensive_threat'])
    pos_df['defensive_threat_rank'] = (
        pos_df['defensive_threat'].rank(pct=True) * 100
    ).round(2)

    return pos_df


cols = ['name', 'team', '90s', 'reliability', 'fpl_pos', 'now_cost',
        'tackles_won_p90_z', 'interceptions_p90_z', 'clearances_p90_z', 'blocks_p90_z', 'recoveries_p90_z',
        'defensive_threat', 'defensive_threat_score', 'defensive_threat_rank']

defense_frames = []

for pos, label in [('MID', 'Midfielders'), ('DEF', 'Defenders'), ('FWD', 'Forwards')]:
    pos_df = compute_defensive_threat_score(z_scores, pos)
    defense_frames.append(pos_df)
    #display(f"{label} Defensive threat score:", pos_df[cols].sort_values("defensive_threat", ascending=False).head(200).reset_index(drop=True))

defensive_df = pd.concat(defense_frames, ignore_index=True)

In [39]:
#Creativity metrics per 90s
def compute_90s(df, columns, mins):
    df = df.copy()
    df = df[df['minutes'] >= mins]
    df = df[df["fpl_pos"].isin(['MID', 'DEF', 'FWD'])]
    df['90s'] = df['minutes'] / 90
    df['reliability'] = df['minutes'] / (df['minutes'].max())
    per_90s = df[columns].div(df['90s'], axis=0)
    per_90s.columns = [f"{col}_p90" for col in columns]
    return pd.concat([df[['name', 'team', 'fpl_pos', 'now_cost', '90s', 'reliability']], per_90s], axis=1)



creativity_cols = ['key_passes', 'big_chances_created', 'assists', 'xa']
cols = ['name', 'team', 'fpl_pos', '90s', 'reliability', 'now_cost'] + [f"{col}_p90" for col in creativity_cols]
per_90s = compute_90s(players_passing_df, creativity_cols, 450)


#z-scores
def compute_z_scores(df, columns):
    df = df.copy()
    z_cols = [f'{column}_z' for column in columns]

    df[z_cols] = (
        df.groupby('fpl_pos')[columns]
        .transform(lambda column: zscore(column, nan_policy='omit'))
    )
    return pd.concat([df[['name', 'team', 'fpl_pos', 'now_cost', '90s', 'reliability']], df[z_cols]], axis=1)

creativity_cols = ['key_passes_p90', 'big_chances_created_p90', 'assists_p90', 'xa_p90']
cols = ['name', 'team', 'fpl_pos', 'now_cost'] + [f"{col}_z" for col in creativity_cols]
z_scores = compute_z_scores(per_90s, creativity_cols)

def compute_creativity_score(df, position):
    pos_df = df.loc[df['fpl_pos'].eq(position)].copy()

    pos_df['creativity'] = pos_df['reliability'] * (
        0.25 * pos_df['key_passes_p90_z']
        + 0.15 * pos_df['big_chances_created_p90_z']
        + 0.15 * pos_df['assists_p90_z']
        + 0.45 * pos_df['xa_p90_z']
    ) * 100

    pos_df['creativity'] = pos_df['creativity'].round(2)
    pos_df['creativity_score'] = minmax_score(pos_df['creativity'])
    pos_df['creativity_rank'] = (
        pos_df['creativity'].rank(pct=True) * 100
    ).round().astype(int)

    return pos_df


cols = ['name', 'team', '90s', 'reliability', 'fpl_pos', 'now_cost', 'key_passes_p90_z', 'big_chances_created_p90_z', 'assists_p90_z', 'xa_p90_z',
        'creativity', 'creativity_score', 'creativity_rank']

creative_frames = []

for pos, label in [('MID', 'Midfielders'), ('DEF', 'Defenders'), ('FWD', 'Forwards')]:
    pos_df = compute_creativity_score(z_scores, pos)
    creative_frames.append(pos_df)
    #display(f"{label} Creativity score:", pos_df[cols].sort_values("creativity_score", ascending=False).reset_index(drop=True))

creative_df = pd.concat(creative_frames, ignore_index=True)

In [40]:
print(defense_df.columns.tolist())

['player_id', 'tackles_won', 'blocks', 'interceptions', 'clearances', 'recoveries']

In [41]:
merge_keys = ['name', 'team', 'fpl_pos']

players_scores_df = (
    goals_df[
        merge_keys
        + [
            'goal_threat_score',
            'goal_threat_rank',
        ]
    ]
    .merge(
        defensive_df[
            merge_keys
            + [
                'defensive_threat_score',
                'defensive_threat_rank',
            ]
        ],
        on=merge_keys,
        how='left',
        validate='one_to_one',
    )
    .merge(
        creative_df[
            merge_keys
            + [
                'creativity_score',
                'creativity_rank',
            ]
        ],
        on=merge_keys,
        how='left',
        validate='one_to_one',
    )
)

players_scores_df = players_scores_df.rename(
    columns={
        'goal_threat_rank': 'goal_percentile',
        'defensive_threat_rank': 'defensive_percentile',
        'creativity_rank': 'creativity_percentile',
    }
)

In [42]:
ARCHETYPE_MAP = {
    'FWD': {
        frozenset({'G'}): 'Finisher',
        frozenset({'C'}): 'Creative Forward',
        frozenset({'D'}): 'Pressing Forward',
        frozenset({'G', 'C'}): 'Complete Forward',
        frozenset({'G', 'D'}): 'Pressing Finisher',
        frozenset({'C', 'D'}): 'Pressing Link Forward',
        frozenset({'G', 'C', 'D'}): 'Complete Two-Way Forward',
    },
    'MID': {
        frozenset({'G'}): 'Goal-Scoring Midfielder',
        frozenset({'C'}): 'Playmaker',
        frozenset({'D'}): 'Ball-Winning Midfielder',
        frozenset({'G', 'C'}): 'Attacking Playmaker',
        frozenset({'G', 'D'}): 'Box-to-Box Midfielder',
        frozenset({'C', 'D'}): 'Deep-Lying Playmaker',
        frozenset({'G', 'C', 'D'}): 'Complete Midfielder',
    },
    'DEF': {
        frozenset({'G'}): 'Goal-Threat Defender',
        frozenset({'C'}): 'Creative Defender',
        frozenset({'D'}): 'Defensive Stopper',
        frozenset({'G', 'C'}): 'Attacking Defender',
        frozenset({'G', 'D'}): 'Two-Way Defender',
        frozenset({'C', 'D'}): 'Defensive Creator',
        frozenset({'G', 'C', 'D'}): 'Complete Defender',
    },
}

In [43]:
def assign_production_profile(row):
    scores = {
        'G': row['goal_percentile'],
        'C': row['creativity_percentile'],
        'D': row['defensive_percentile'],
    }

    if any(pd.isna(value) for value in scores.values()):
        return pd.Series({
            'production_archetype': 'Insufficient Data',
            'production_tier': 'Unrated',
            'primary_strength': None,
        })

    primary = max(scores, key=scores.get)
    primary_score = scores[primary]

    # Players below the 40th percentile in everything are genuinely
    # low-production rather than balanced.
    if primary_score < 40:
        archetype = 'Low-Production'
    elif max(scores.values()) - min(scores.values()) <= 10:
        archetype = 'Balanced Profile'
    else:
        traits = {primary}

        for trait, score in scores.items():
            if (
                trait != primary
                and score >= 60
                and primary_score - score <= 15
            ):
                traits.add(trait)

        archetype = ARCHETYPE_MAP[row['fpl_pos']][frozenset(traits)]

    if primary_score >= 90:
        tier = 'Elite'
    elif primary_score >= 75:
        tier = 'High'
    elif primary_score >= 50:
        tier = 'Average'
    else:
        tier = 'Low'

    strength_names = {
        'G': 'Goal Threat',
        'C': 'Creativity',
        'D': 'Defensive Activity',
    }

    return pd.Series({
        'production_archetype': archetype,
        'production_tier': tier,
        'primary_strength': strength_names[primary],
    })

profile_columns = players_scores_df.apply(
    assign_production_profile,
    axis=1,
)

players_scores_df = pd.concat(
    [players_scores_df, profile_columns],
    axis=1,
)

In [44]:
display(
    players_scores_df[
        [
            'name',
            'team',
            'fpl_pos',
            'goal_percentile',
            'creativity_percentile',
            'defensive_percentile',
            'production_archetype',
            'production_tier',
            'primary_strength',
        ]
    ].sort_values(
        ['fpl_pos', 'production_tier', 'goal_percentile'],
        ascending=[True, True, False],
    )
)

,name,team,fpl_pos,goal_percentile,creativity_percentile,defensive_percentile,production_archetype,production_tier,primary_strength
323,Santiago Bueno,WOL,DEF,73,27,14.97,Goal-Threat Defender,Average,Goal Threat
268,Nathan Aké,MCI,DEF,71,67,27.21,Attacking Defender,Average,Goal Threat
284,Sven Botman,NEW,DEF,70,61,72.11,Complete Defender,Average,Defensive Activity
278,Harry Maguire,MUN,DEF,69,48,22.45,Goal-Threat Defender,Average,Goal Threat
300,Omar Alderete,SUN,DEF,69,10,32.65,Goal-Threat Defender,Average,Goal Threat
...,...,...,...,...,...,...,...,...,...
146,Dan Ndoye,NFO,MID,32,48,48.62,Ball-Winning Midfielder,Low,Defensive Activity
132,Anthony Elanga,NEW,MID,30,38,8.29,Low-Production,Low,Creativity
66,Will Hughes,CRY,MID,17,30,43.65,Ball-Winning Midfielder,Low,Defensive Activity
99,Ilia Gruev,LEE,MID,17,40,35.36,Playmaker,Low,Creativity
78,Idrissa Gana Gueye,EVE,MID,7,7,0.55,Low-Production,Low,Goal Threat

In [45]:
# merge All scores into one dataframe
players_scores_df = goals_df.copy()

for src_df, score_cols in [
    (defensive_df, ['defensive_threat', 'defensive_threat_score', 'defensive_threat_rank']),
    (creative_df, ['creativity', 'creativity_score', 'creativity_rank']),
]:
    available = [c for c in ['name'] + score_cols if c in src_df.columns]
    players_scores_df = players_scores_df.merge(src_df[available], on='name', how='left')


#Assign archetypes based on goal threat, defensive threat, and creativity ranks
def assign_archetype(row):
    if row['fpl_pos'] == 'FWD':
        if row['goal_threat_score'] >= 70:
            return 'Elite Goal Threat'
        elif row['goal_threat_score'] >= 50 and row['goal_threat_score'] < 70:
            return 'Goal Threat'
        elif row['defensive_threat_score'] >= 65:
            return 'Elite Defensive Threat'
        elif row['defensive_threat_score'] >= 40 and row['defensive_threat_score'] < 65:
            return 'Defensive Threat'
        else:
            return 'Balanced'
        
    if row['fpl_pos'] == 'MID':
            if row['goal_threat_score'] >= 85:
                return 'Elite Goal Threat'
            elif row['goal_threat_score'] >= 70 and row['goal_threat_score'] < 85:
                return 'Goal Threat'
            elif row['defensive_threat_score'] >= 85:
                return 'Elite Defensive Threat'
            elif row['defensive_threat_score'] >= 65 and row['defensive_threat_score'] < 85:
                return 'Defensive Threat'        
            else:
                return 'Balanced'

    if row['fpl_pos'] == 'DEF':
                if row['goal_threat_score'] >= 70:
                    return 'Elite Goal Threat'
                elif row['goal_threat_score'] >= 55 and row['goal_threat_score'] < 70:
                    return 'Goal Threat'
                elif row['defensive_threat_score'] >= 80:
                    return 'Elite Defensive Threat'
                elif row['defensive_threat_score'] >= 60 and row['defensive_threat_score'] < 80:
                    return 'Defensive Threat'
                else:
                    return 'Balanced'

    

players_scores_df['archetype'] = players_scores_df.apply(assign_archetype, axis=1)

goal_getter = players_scores_df[players_scores_df['archetype'].eq('Defensive Threat')].sort_values("goal_threat_score", ascending=False).reset_index(drop=True)


#display(goal_getter)

In [46]:
# Reliability-adjusted metric-level shrinkage
#
# A player's per-90 rate is pulled toward the minutes-weighted mean for
# their FPL position. More minutes means less shrinkage:
# adjusted_rate = reliability * player_rate + (1 - reliability) * position_mean

POSITIONS = ['MID', 'DEF', 'FWD']


def _position_zscore(series):
    std = series.std(ddof=0)
    if pd.isna(std) or std == 0:
        return pd.Series(0.0, index=series.index)
    return (series - series.mean()) / std


def prepare_shrunk_metrics(df, metric_cols, mins=450, prior_minutes=450):
    result = df.loc[
        (df['minutes'] >= mins) & df['fpl_pos'].isin(POSITIONS)
    ].copy()

    result['90s'] = result['minutes'] / 90
    result['reliability'] = (
        result['minutes'] / (result['minutes'] + prior_minutes)
    )

    position_90s = result.groupby('fpl_pos')['90s'].transform('sum')

    for metric in metric_cols:
        p90_col = f'{metric}_p90'
        shrunk_col = f'{metric}_p90_shrunk'
        z_col = f'{metric}_p90_z'

        result[p90_col] = result[metric] / result['90s']

        # Aggregate totals / aggregate 90s gives a minutes-weighted prior.
        position_mean = (
            result.groupby('fpl_pos')[metric].transform('sum') / position_90s
        )
        result[shrunk_col] = (
            result['reliability'] * result[p90_col]
            + (1 - result['reliability']) * position_mean
        )
        result[z_col] = (
            result.groupby('fpl_pos')[shrunk_col]
            .transform(_position_zscore)
        )

    return result


def _scale_0_100(series):
    spread = series.max() - series.min()
    if pd.isna(spread) or spread == 0:
        return pd.Series(50.0, index=series.index)
    return (series - series.min()) / spread * 100


def add_position_composite(df, weights, prefix):
    result = df.copy()
    raw_col = f'{prefix}_raw'
    score_col = f'{prefix}_score'
    percentile_col = f'{prefix}_percentile'
    rank_col = f'{prefix}_rank'

    # Reliability has already been applied to each metric; do not multiply again.
    result[raw_col] = sum(
        weight * result[column] for column, weight in weights.items()
    )
    result[score_col] = (
        result.groupby('fpl_pos')[raw_col]
        .transform(_scale_0_100)
        .round(2)
    )
    result[percentile_col] = (
        result.groupby('fpl_pos')[raw_col]
        .rank(method='average', pct=True)
        .mul(100)
        .round(2).astype(int)
    )
    result[rank_col] = (
        result.groupby('fpl_pos')[raw_col]
        .rank(method='min', ascending=False)
        .astype('Int64')
    )
    return result


# Goal threat
goal_metrics = ['goals_scored', 'xg', 'shots_total', 'shots_on_target']
shrunk_goal_scores = prepare_shrunk_metrics(
    players_shooting_df, goal_metrics, mins=450, prior_minutes=450
)
shrunk_goal_scores['gls_performance_shrunk'] = (
    shrunk_goal_scores['goals_scored_p90_shrunk']
    - shrunk_goal_scores['xg_p90_shrunk']
)
shrunk_goal_scores['gls_performance_z'] = (
    shrunk_goal_scores.groupby('fpl_pos')['gls_performance_shrunk']
    .transform(_position_zscore)
)
shrunk_goal_scores = add_position_composite(
    shrunk_goal_scores,
    {
        'xg_p90_z': 0.55,
        'shots_on_target_p90_z': 0.20,
        'shots_total_p90_z': 0.15,
        'gls_performance_z': 0.10,
    },
    'goal_threat',
)


# Defensive activity
defensive_metrics = [
    'tackles_won', 'interceptions', 'clearances', 'blocks', 'recoveries'
]
shrunk_defensive_scores = prepare_shrunk_metrics(
    players_defense_df, defensive_metrics, mins=450, prior_minutes=450
)
shrunk_defensive_scores = add_position_composite(
    shrunk_defensive_scores,
    {
        'tackles_won_p90_z': 0.20,
        'interceptions_p90_z': 0.25,
        'clearances_p90_z': 0.25,
        'blocks_p90_z': 0.15,
        'recoveries_p90_z': 0.15,
    },
    'defensive_threat',
)


# Creativity
creativity_metrics = ['key_passes', 'big_chances_created', 'assists', 'xa']
shrunk_creativity_scores = prepare_shrunk_metrics(
    players_passing_df, creativity_metrics, mins=450, prior_minutes=450
)
shrunk_creativity_scores = add_position_composite(
    shrunk_creativity_scores,
    {
        'key_passes_p90_z': 0.25,
        'big_chances_created_p90_z': 0.20,
        'assists_p90_z': 0.05,
        'xa_p90_z': 0.50,
    },
    'creativity',
)


# Preview the top 10 in each position for each model.
for label, frame, prefix in [
    ('Goal threat', shrunk_goal_scores, 'goal_threat'),
    ('Defensive threat', shrunk_defensive_scores, 'defensive_threat'),
    ('Creativity', shrunk_creativity_scores, 'creativity'),
]:
    preview_cols = [
        'name', 'team', 'fpl_pos', 'minutes', 'reliability',
        f'{prefix}_score', f'{prefix}_percentile', f'{prefix}_rank',
    ]
    preview = (
        frame.sort_values(['fpl_pos', f'{prefix}_rank'])
        .groupby('fpl_pos', group_keys=False)
        .head(10)[preview_cols]
        .reset_index(drop=True)
    )
    display(f'{label}: reliability-adjusted top 10 by position', preview)

'Goal threat: reliability-adjusted top 10 by position'

,name,team,fpl_pos,minutes,reliability,goal_threat_score,goal_threat_percentile,goal_threat_rank
0,Nico O’Reilly,MCI,DEF,2643,0.854510,100.00,100,1
1,Patrick Dorgu,MUN,DEF,1440,0.761905,97.14,99,2
2,Rodrigo Gomes,WOL,DEF,954,0.679487,95.68,98,3
3,Riccardo Calafiori,ARS,DEF,1697,0.790405,75.03,97,4
4,Malick Thiaw,NEW,DEF,2963,0.868151,73.73,97,5
5,Keane Lewis-Potter,BRE,DEF,1960,0.813278,73.51,96,6
6,Daniel Ballard,SUN,DEF,2144,0.826523,67.85,95,7
7,Daniel Muñoz,CRY,DEF,2400,0.842105,67.00,95,8
8,Virgil van Dijk,LIV,DEF,3420,0.883721,63.64,94,9
9,Jurriën Timber,ARS,DEF,2452,0.844935,62.00,93,10
10,Erling Haaland,MCI,FWD,2953,0.867764,100.00,100,1
11,Benjamin Šeško,MUN,FWD,1630,0.783654,77.85,97,2
12,Taiwo Awoniyi,NFO,FWD,480,0.516129,67.61,95,3
13,Thiago,BRE,FWD,3282,0.879421,64.00,93,4
14,Lukas Nmecha,LEE,FWD,1065,0.702970,62.08,90,5
15,Jean-Philippe Mateta,CRY,FWD,2210,0.830827,61.67,88,6
16,Ollie Watkins,AVL,FWD,2833,0.862930,59.37,86,7
17,William Osula,NEW,FWD,805,0.641434,59.35,84,8
18,Hugo Ekitike,LIV,FWD,1797,0.799733,58.92,81,9
19,Dominic Calvert-Lewin,LEE,FWD,2721,0.858089,56.77,79,10
20,Donyell Malen,AVL,MID,640,0.587156,100.00,100,1
21,Cole Palmer,CHE,MID,1954,0.812812,95.89,99,2
22,Bryan Mbeumo,MUN,MID,2611,0.852989,90.41,98,3
23,Antoine Semenyo,MCI,MID,3200,0.876712,85.97,98,4
24,Omar Marmoush,MCI,MID,691,0.605609,84.29,97,5
25,Ismaïla Sarr,CRY,MID,2173,0.828441,82.63,97,6
26,David Brooks,BOU,MID,1188,0.725275,80.58,96,7
27,Anthony Gordon,NEW,MID,1798,0.799822,80.51,96,8
28,Morgan Gibbs-White,NFO,MID,3101,0.873275,77.69,95,9
29,Harvey Barnes,NEW,MID,1951,0.812578,76.46,95,10

'Defensive threat: reliability-adjusted top 10 by position'

,name,team,fpl_pos,minutes,reliability,defensive_threat_score,defensive_threat_percentile,defensive_threat_rank
0,Oliver Scarles,WHU,DEF,656,0.593128,100.00,100,1
1,Antonee Robinson,FUL,DEF,1487,0.767682,89.75,99,2
2,Noussair Mazraoui,MUN,DEF,977,0.684653,76.01,98,3
3,Marcos Senesi,BOU,DEF,3288,0.879615,75.73,97,4
4,Tyrick Mitchell,CRY,DEF,3253,0.878477,74.89,97,5
5,Olivier Boscagli,BHA,DEF,799,0.639712,73.80,96,6
6,Abdukodir Khusanov,MCI,DEF,1427,0.760256,72.93,95,7
7,Wesley Fofana,CHE,DEF,1718,0.792435,72.42,95,8
8,Conor Bradley,LIV,DEF,928,0.673440,69.69,94,9
9,Cristian Romero,TOT,DEF,1869,0.805951,69.22,93,10
10,Jarrod Bowen,WHU,FWD,3406,0.883299,100.00,100,1
11,Pablo,WHU,FWD,819,0.645390,89.80,97,2
12,Eli Junior Kroupi,BOU,FWD,1663,0.787033,70.72,95,3
13,Mateus Mane,WOL,FWD,1787,0.798838,70.72,93,4
14,Richarlison,TOT,FWD,1954,0.812812,68.63,90,5
15,Thiago,BRE,FWD,3282,0.879421,63.65,88,6
16,Tolu Arokodare,WOL,FWD,1402,0.757019,62.77,86,7
17,Dominic Solanke,TOT,FWD,997,0.689012,62.45,84,8
18,Raúl Jiménez,FUL,FWD,2183,0.829092,54.19,81,9
19,Lukas Nmecha,LEE,FWD,1065,0.702970,53.92,79,10
20,Florentino Luís,BUR,MID,2100,0.823529,100.00,100,1
21,Lewis Cook,BOU,MID,872,0.659607,95.38,99,2
22,Manuel Ugarte Ribeiro,MUN,MID,876,0.660633,94.52,98,3
23,James Garner,EVE,MID,3413,0.883510,93.00,98,4
24,Rodrigo Bentancur,TOT,MID,1880,0.806867,92.95,97,5
25,Casemiro,MUN,MID,2575,0.851240,92.30,97,6
26,Mats Wieffer,BHA,MID,1901,0.808592,91.73,96,7
27,João Palhinha,TOT,MID,2192,0.829674,91.02,96,8
28,Elliot Anderson,NFO,MID,3332,0.881015,88.36,95,9
29,Ryan Sessegnon,FUL,MID,1816,0.801412,84.62,95,10

'Creativity: reliability-adjusted top 10 by position'

,name,team,fpl_pos,minutes,reliability,creativity_score,creativity_percentile,creativity_rank
0,Maxim De Cuyper,BHA,DEF,1404,0.757282,100.00,100,1
1,Jeremie Frimpong,LIV,DEF,1032,0.696356,73.24,99,2
2,Patrick Dorgu,MUN,DEF,1440,0.761905,70.93,98,3
3,Reece James,CHE,DEF,1957,0.813045,66.66,97,4
4,Daniel Muñoz,CRY,DEF,2400,0.842105,62.12,97,5
5,Pedro Porro,TOT,DEF,2793,0.861240,59.19,96,6
6,Ian Maatsen,AVL,DEF,1590,0.779412,58.90,95,7
7,Ben White,ARS,DEF,699,0.608355,55.01,95,8
8,Hugo Bueno,WOL,DEF,2359,0.839801,54.73,94,9
9,Marc Cucurella,CHE,DEF,2706,0.857414,54.54,93,10
10,Jarrod Bowen,WHU,FWD,3406,0.883299,100.00,100,1
11,Kai Havertz,ARS,FWD,577,0.561831,83.46,97,2
12,Mateus Mane,WOL,FWD,1787,0.798838,80.33,95,3
13,Taiwo Awoniyi,NFO,FWD,480,0.516129,77.17,93,4
14,Joshua Zirkzee,MUN,FWD,607,0.574267,71.88,90,5
15,Erling Haaland,MCI,FWD,2953,0.867764,66.92,88,6
16,Pablo,WHU,FWD,819,0.645390,63.59,86,7
17,Richarlison,TOT,FWD,1954,0.812812,62.76,84,8
18,Nick Woltemade,NEW,FWD,1896,0.808184,60.78,81,9
19,João Pedro,CHE,FWD,2658,0.855212,59.70,79,10
20,Bruno Fernandes,MUN,MID,3065,0.871977,100.00,100,1
21,Rayan Cherki,MCI,MID,1772,0.797480,89.13,99,2
22,Jeremy Doku,MCI,MID,1773,0.797571,66.35,98,3
23,Bukayo Saka,ARS,MID,2218,0.831334,57.69,98,4
24,Martin Ødegaard,ARS,MID,1363,0.751793,52.28,97,5
25,David Brooks,BOU,MID,1188,0.725275,48.74,97,6
26,Phil Foden,MCI,MID,2078,0.821994,47.06,96,7
27,Mikkel Damsgaard,BRE,MID,2046,0.819712,46.17,96,8
28,Mohamed Salah,LIV,MID,2144,0.826523,46.00,95,9
29,Rio Ngumoha,LIV,MID,547,0.548646,45.95,95,10

In [47]:
#Players weekly points returned
players_weekly_pts = weekly_df[['name', 'player_id', 'team', 'fpl_pos', 'total_points', 'minutes', 'was_home', 'defensive_contribution', 'goals_scored', 'assists', 'goals_conceded', 'clean_sheets']].copy()


players_weekly_pts['venue'] = players_weekly_pts['was_home'].apply(lambda x: 'Home' if x else 'Away')


# each players home and away points
def compute_home_away_points(df):
    home_away_points = (
        df.groupby(['name', 'team', 'fpl_pos', 'venue'])
        .agg(
            total_points=('total_points', 'sum'),
            games_played=('total_points', 'count'),
            minutes_played=('minutes', 'sum')
        )
        .reset_index()
    )

    home_away_points['points_per_game'] = (
        home_away_points['total_points'] / home_away_points['games_played']
    ).round(2)

    return home_away_points

display(compute_home_away_points(players_weekly_pts).sort_values(['total_points', 'name', 'fpl_pos'], ascending=[False, True, True]).reset_index(drop=True))

,name,team,fpl_pos,venue,total_points,games_played,minutes_played,points_per_game
0,Bruno Fernandes,MUN,MID,Home,124,19,1526,6.53
1,Erling Haaland,MCI,FWD,Home,120,19,1377,6.32
2,Erling Haaland,MCI,FWD,Away,119,19,1576,6.26
3,Bruno Fernandes,MUN,MID,Away,111,19,1539,5.84
4,Casemiro,MUN,MID,Home,107,19,1464,5.63
...,...,...,...,...,...,...,...,...
1727,Ármin Pécsi,LIV,GKP,Home,0,19,0,0.00
1728,İlkay Gündoğan,MCI,MID,Away,0,19,0,0.00
1729,İlkay Gündoğan,MCI,MID,Home,0,19,0,0.00
1730,Łukasz Fabiański,WHU,GKP,Away,0,17,0,0.00
1731,Łukasz Fabiański,WHU,GKP,Home,0,18,0,0.00

In [48]:
#defcon points return leaders
def compute_defcon_returns(df, position):
    if position not in ['MID', 'DEF', 'FWD']:
        return "Enter a valid position"
    
    threshold = 10 if position == 'DEF' else 12
    pos_df = df.loc[df['fpl_pos'].eq(position)].copy()
    
    result = (
        pos_df.groupby(['name', 'team', 'fpl_pos', 'venue'])['defensive_contribution']
        .apply(lambda x: (x > threshold).sum())
        .reset_index(name='defcon_returns')
    )
    return result

for pos, label in [('MID', 'Midfielders'), ('DEF', 'Defenders'), ('FWD', 'Forwards')]:
    pos_df = compute_defcon_returns(players_weekly_pts, pos)
    display(f"{label} Defensive contribution score:", pos_df.sort_values(["defcon_returns", "team", "name"], ascending=[False, True, True]).reset_index(drop=True))

'Midfielders Defensive contribution score:'

                name team fpl_pos venue  defcon_returns
0    Elliot Anderson  NFO     MID  Away              13
1       James Garner  EVE     MID  Away              11
2       Ethan Ampadu  LEE     MID  Away              10
3    Elliot Anderson  NFO     MID  Home              10
4        André Gomes  WOL     MID  Away               8
..               ...  ...     ...   ...             ...
787  Tawanda Chirewa  WOL     MID  Home               0
788  Temple Ojinnaka  WOL     MID  Away               0
789  Temple Ojinnaka  WOL     MID  Home               0
790       Tom Edozie  WOL     MID  Away               0
791       Tom Edozie  WOL     MID  Home               0

[792 rows x 5 columns]

'Defenders Defensive contribution score:'

                        name team fpl_pos venue  defcon_returns
0              Marcos Senesi  BOU     DEF  Away              12
1            James Tarkowski  EVE     DEF  Away              11
2              Marcos Senesi  BOU     DEF  Home               9
3    Konstantinos Mavropanos  WHU     DEF  Away               9
4             Nathan Collins  BRE     DEF  Home               8
..                       ...  ...     ...   ...             ...
541               Pedro Lima  WOL     DEF  Home               0
542            Rodrigo Gomes  WOL     DEF  Away               0
543            Rodrigo Gomes  WOL     DEF  Home               0
544          Saheed Olagunju  WOL     DEF  Away               0
545          Saheed Olagunju  WOL     DEF  Home               0

[546 rows x 5 columns]

'Forwards Defensive contribution score:'

               name team fpl_pos venue  defcon_returns
0      Jarrod Bowen  WHU     FWD  Away               3
1            Thiago  BRE     FWD  Away               1
2      Jarrod Bowen  WHU     FWD  Home               1
3       Mateus Mane  WOL     FWD  Home               1
4     Gabriel Jesus  ARS     FWD  Away               0
..              ...  ...     ...   ...             ...
192   Nathan Fraser  WOL     FWD  Home               0
193  Sasa Kalajdzic  WOL     FWD  Away               0
194  Sasa Kalajdzic  WOL     FWD  Home               0
195  Tolu Arokodare  WOL     FWD  Away               0
196  Tolu Arokodare  WOL     FWD  Home               0

[197 rows x 5 columns]

In [49]:
#points return leaders
def compute_points_returns(df, position):
  
    threshold = 3
    pos_df = df.loc[df['fpl_pos'].eq(position)].copy()
    
    result = (
        pos_df.groupby(['name', 'team', 'fpl_pos', 'venue'])['total_points']
        .apply(lambda x: (x > threshold).sum())
        .reset_index(name='points_returns')
    )
    return result

for pos, label in [('MID', 'Midfielders'), ('DEF', 'Defenders'), ('FWD', 'Forwards'), ('GKP', 'Goalkeepers')]:
    pos_df = compute_points_returns(players_weekly_pts, pos)
    display(f"{label} Points contribution score:", pos_df.sort_values(["points_returns", "team", "name"], ascending=[False, True, True]).reset_index(drop=True))

'Midfielders Points contribution score:'

                name team fpl_pos venue  points_returns
0    Bruno Fernandes  MUN     MID  Home              14
1    Elliot Anderson  NFO     MID  Away              13
2       James Garner  EVE     MID  Away              12
3           Casemiro  MUN     MID  Home              12
4    Elliot Anderson  NFO     MID  Home              12
..               ...  ...     ...   ...             ...
787  Tawanda Chirewa  WOL     MID  Away               0
788  Tawanda Chirewa  WOL     MID  Home               0
789  Temple Ojinnaka  WOL     MID  Away               0
790  Temple Ojinnaka  WOL     MID  Home               0
791       Tom Edozie  WOL     MID  Away               0

[792 rows x 5 columns]

'Defenders Points contribution score:'

                  name team fpl_pos venue  points_returns
0    Gabriel Magalhães  ARS     DEF  Home              13
1      Adrien Truffert  BOU     DEF  Home              12
2        Nico O’Reilly  MCI     DEF  Home              12
3        Nordi Mukiele  SUN     DEF  Home              12
4        Marcos Senesi  BOU     DEF  Home              11
..                 ...  ...     ...   ...             ...
541         Pedro Lima  WOL     DEF  Away               0
542         Pedro Lima  WOL     DEF  Home               0
543      Rodrigo Gomes  WOL     DEF  Away               0
544    Saheed Olagunju  WOL     DEF  Away               0
545    Saheed Olagunju  WOL     DEF  Home               0

[546 rows x 5 columns]

'Forwards Points contribution score:'

               name team fpl_pos venue  points_returns
0    Erling Haaland  MCI     FWD  Away              11
1    Erling Haaland  MCI     FWD  Home              11
2       Richarlison  TOT     FWD  Away              10
3      Jarrod Bowen  WHU     FWD  Away              10
4      Jarrod Bowen  WHU     FWD  Home              10
..              ...  ...     ...   ...             ...
192    Leon Chiwome  WOL     FWD  Home               0
193   Nathan Fraser  WOL     FWD  Away               0
194   Nathan Fraser  WOL     FWD  Home               0
195  Sasa Kalajdzic  WOL     FWD  Away               0
196  Sasa Kalajdzic  WOL     FWD  Home               0

[197 rows x 5 columns]

'Goalkeepers Points contribution score:'

                     name team fpl_pos venue  points_returns
0              David Raya  ARS     GKP  Home              11
1    Gianluigi Donnarumma  MCI     GKP  Home              11
2              David Raya  ARS     GKP  Away               8
3             Robin Roefs  SUN     GKP  Home               8
4       Caoimhín Kelleher  BRE     GKP  Home               7
..                    ...  ...     ...   ...             ...
192           Josh Gracey  WOL     GKP  Away               0
193           Josh Gracey  WOL     GKP  Home               0
194         Sam Johnstone  WOL     GKP  Away               0
195         Sam Johnstone  WOL     GKP  Home               0
196              Tom King  WOL     GKP  Home               0

[197 rows x 5 columns]

In [50]:
#goals return leaders
def compute_goals_returns(df, position):
    if position not in ['MID', 'DEF', 'FWD']:
        return "Enter a valid position"

    threshold = 0
    pos_df = df.loc[df['fpl_pos'].eq(position)].copy()
    
    result = (
        pos_df.groupby(['name', 'team', 'fpl_pos', 'venue'])['goals_scored']
        .apply(lambda x: (x > threshold).sum())
        .reset_index(name='goals_returns')
    )
    return result

for pos, label in [('MID', 'Midfielders'), ('DEF', 'Defenders'), ('FWD', 'Forwards')]:
    pos_df = compute_goals_returns(players_weekly_pts, pos)
    display(f"{label} Goals contribution score:", pos_df.sort_values(["goals_returns", "team", "name"], ascending=[False, True, True]).reset_index(drop=True))

'Midfielders Goals contribution score:'

                   name team fpl_pos venue  goals_returns
0          Harry Wilson  FUL     MID  Home              8
1       Bruno Guimarães  NEW     MID  Home              8
2    Morgan Gibbs-White  NFO     MID  Away              8
3              Casemiro  MUN     MID  Home              7
4         Matheus Cunha  MUN     MID  Home              6
..                  ...  ...     ...   ...            ...
787     Tawanda Chirewa  WOL     MID  Away              0
788     Tawanda Chirewa  WOL     MID  Home              0
789     Temple Ojinnaka  WOL     MID  Away              0
790     Temple Ojinnaka  WOL     MID  Home              0
791          Tom Edozie  WOL     MID  Away              0

[792 rows x 5 columns]

'Defenders Goals contribution score:'

                 name team fpl_pos venue  goals_returns
0        Daniel Muñoz  CRY     DEF  Away              4
1     Virgil van Dijk  LIV     DEF  Away              4
2       Michael Keane  EVE     DEF  Home              3
3       Nico O’Reilly  MCI     DEF  Home              3
4    Micky van de Ven  TOT     DEF  Away              3
..                ...  ...     ...   ...            ...
541   Saheed Olagunju  WOL     DEF  Home              0
542        Toti Gomes  WOL     DEF  Away              0
543        Toti Gomes  WOL     DEF  Home              0
544   Yerson Mosquera  WOL     DEF  Away              0
545   Yerson Mosquera  WOL     DEF  Home              0

[546 rows x 5 columns]

'Forwards Goals contribution score:'

                  name team fpl_pos venue  goals_returns
0       Erling Haaland  MCI     FWD  Away             10
1       Erling Haaland  MCI     FWD  Home             10
2               Thiago  BRE     FWD  Home              8
3           João Pedro  CHE     FWD  Home              8
4    Eli Junior Kroupi  BOU     FWD  Home              7
..                 ...  ...     ...   ...            ...
192       Leon Chiwome  WOL     FWD  Home              0
193      Nathan Fraser  WOL     FWD  Away              0
194      Nathan Fraser  WOL     FWD  Home              0
195     Sasa Kalajdzic  WOL     FWD  Away              0
196     Sasa Kalajdzic  WOL     FWD  Home              0

[197 rows x 5 columns]

In [51]:
team_elo = elo_df.copy()

team_elo = elo_df.copy()

result = team_elo.groupby(['team', 'team_id'])['elo_preseason'].mean().round().astype(int).reset_index()

league_elo_mean = result['elo_preseason'].mean()
league_std = result['elo_preseason'].std()
print(f"The average elo in the Premier league is {league_elo_mean}")
print(f"The average std in the Premier league is {league_std}")

#elo z-scores
result['elo_z'] = zscore(result['elo_preseason'])
display(result[['team', 'team_id', 'elo_preseason', 'elo_z']].sort_values('elo_preseason', ascending=False).reset_index(drop=True))

The average elo in the Premier league is 1819.4
The average std in the Premier league is 117.84039160973984

   team       team_id  elo_preseason     elo_z
0   ARS      1dd1f33c           2064  2.129612
1   MCI      b11c2f05           1971  1.319907
2   AVL      bcc4ae28           1921  0.884581
3   MUN      767ff900           1915  0.832342
4   LIV      259f237e           1911  0.797516
5   BOU      56f0abca           1872  0.457962
6   BHA      5dbeea62           1842  0.196767
7   NEW      ddbd77d6           1838  0.161941
8   BRE      8331d109           1837  0.153235
9   CHE      1464d629           1831  0.100995
10  NFO      03a0d347           1822  0.022637
11  FUL      049e06ec           1813 -0.055722
12  CRY      53c995cd           1804 -0.134080
13  EVE      f5ee07af           1803 -0.142787
14  LEE      cd881c68           1797 -0.195026
15  TOT      2d0845b3           1777 -0.369156
16  SUN      b842021f           1736 -0.726123
17  COV  ce4d980327c7           1661 -1.379111
18  IPS      53548284           1640 -1.561948
19  HUL      c882a163           1533 -2.493544

In [52]:
team_attack = team_attack_df.copy()

#display(team_attack.sort_values('xg', ascending=False).reset_index(drop=True))

corr_matrix = team_attack.corr(numeric_only=True, method='spearman')
#display(corr_matrix)

#sns.heatmap(corr_matrix, annot=True, cmap='coolwarm', vmin=-1, vmax=1)
#plt.show()

#compute per match 
def compute_per_match(df, columns):
    team_match = df.copy()

    per_match = team_match[columns].div(team_match['matches_covered'], axis=0)
    per_match.columns = [f"{col}_pm" for col in columns]
    return pd.concat([team_match[['team', 'team_id']], per_match], axis=1)

cols = ['xg', 'np_xg', 'shots_total', 'shots_on_target', 'big_chance_shots', 'key_passes',
       'big_chances_created', 'shot_creating_actions', 'goal_creating_actions',
       'touches_penalty_area', 'box_entries']

per_match = compute_per_match(team_attack, cols)
print(per_match.columns)


#compute z-scores
def compute_z(df, columns):
    team_df = df.copy()

    att_z_scores = team_df[columns].apply(
            lambda column: zscore(column, nan_policy='omit')
        )
    att_z_scores.columns = [f"{col}_z" for col in columns]

    return pd.concat([team_df[['team']], att_z_scores], axis=1)

att_cols = ['xg_pm', 'np_xg_pm', 'shots_total_pm', 'shots_on_target_pm', 'big_chance_shots_pm', 'key_passes_pm',
       'big_chances_created_pm', 'shot_creating_actions_pm', 'goal_creating_actions_pm',
       'touches_penalty_area_pm', 'box_entries_pm']

att_z_scores = compute_z(per_match, att_cols)

print(att_z_scores.columns)

cols = ['xg_pm_z', 'np_xg_pm_z',
       'shots_total_pm_z', 'shots_on_target_pm_z', 'big_chance_shots_pm_z',
       'key_passes_pm_z', 'big_chances_created_pm_z',
       'shot_creating_actions_pm_z', 'goal_creating_actions_pm_z',
       'touches_penalty_area_pm_z', 'box_entries_pm_z']
att_z_scores['attMetric_z'] = att_z_scores[cols].mean(axis=1)


#display(att_z_scores)

Index(['team', 'team_id', 'xg_pm', 'np_xg_pm', 'shots_total_pm',
       'shots_on_target_pm', 'big_chance_shots_pm', 'key_passes_pm',
       'big_chances_created_pm', 'shot_creating_actions_pm',
       'goal_creating_actions_pm', 'touches_penalty_area_pm',
       'box_entries_pm'],
      dtype='str')
Index(['team', 'xg_pm_z', 'np_xg_pm_z', 'shots_total_pm_z',
       'shots_on_target_pm_z', 'big_chance_shots_pm_z', 'key_passes_pm_z',
       'big_chances_created_pm_z', 'shot_creating_actions_pm_z',
       'goal_creating_actions_pm_z', 'touches_penalty_area_pm_z',
       'box_entries_pm_z'],
      dtype='str')

In [53]:
print(team_def_df.columns)

Index(['team', 'team_id', 'xga', 'np_xga', 'matches_covered', 'shots_conceded',
       'shots_on_target_against', 'big_chances_conceded',
       'box_entries_against'],
      dtype='str')

In [54]:
team_defense = team_def_df.copy()

#display(team_defense.sort_values('xg', ascending=False).reset_index(drop=True))

corr_matrix = team_defense.corr(numeric_only=True, method='spearman')
#display(corr_matrix)

#sns.heatmap(corr_matrix, annot=True, cmap='coolwarm', vmin=-1, vmax=1)
#plt.show()

#compute per match 
def compute_per_match(df, columns):
    team_match = df.copy()

    per_match = team_match[columns].div(team_match['matches_covered'], axis=0)
    per_match.columns = [f"{col}_pm" for col in columns]
    return pd.concat([team_match[['team', 'team_id']], per_match], axis=1)

cols = ['xga', 'np_xga', 'shots_conceded',
       'shots_on_target_against', 'big_chances_conceded',
       'box_entries_against']

per_match = compute_per_match(team_defense, cols)
print(per_match.columns)


#compute z-scores
def compute_z(df, columns):
    team_df = df.copy()

    def_z_scores = team_df[columns].apply(
            lambda column: zscore(column, nan_policy='omit')
        )
    def_z_scores.columns = [f"{col}_z" for col in columns]

    return pd.concat([team_df[['team']], def_z_scores], axis=1)

att_cols = ['xga_pm', 'np_xga_pm', 'shots_conceded_pm',
       'shots_on_target_against_pm', 'big_chances_conceded_pm',
       'box_entries_against_pm']

def_z_scores = compute_z(per_match, att_cols)

print(def_z_scores.columns)

cols = ['xga_pm_z', 'np_xga_pm_z', 'shots_conceded_pm_z',
       'shots_on_target_against_pm_z', 'big_chances_conceded_pm_z',
       'box_entries_against_pm_z']
def_z_scores['defMetric_z'] = def_z_scores[cols].mean(axis=1)
def_z_scores['defMetric_z'] = -(def_z_scores['defMetric_z'])

display(def_z_scores)

Index(['team', 'team_id', 'xga_pm', 'np_xga_pm', 'shots_conceded_pm',
       'shots_on_target_against_pm', 'big_chances_conceded_pm',
       'box_entries_against_pm'],
      dtype='str')
Index(['team', 'xga_pm_z', 'np_xga_pm_z', 'shots_conceded_pm_z',
       'shots_on_target_against_pm_z', 'big_chances_conceded_pm_z',
       'box_entries_against_pm_z'],
      dtype='str')

,team,xga_pm_z,np_xga_pm_z,shots_conceded_pm_z,shots_on_target_against_pm_z,big_chances_conceded_pm_z,box_entries_against_pm_z,defMetric_z
0,ARS,-2.679789,-2.584784,-2.407358,-2.925709,-2.691616,-2.470263,2.626586
1,MCI,-1.247058,-1.178335,-1.533544,-1.308812,-0.680638,-1.935574,1.313994
2,MUN,-0.840707,-0.887517,-0.499531,-0.697013,-0.990020,0.191300,0.620581
3,AVL,-0.154155,0.066094,0.214085,0.264384,0.402195,-0.414681,-0.062987
4,LIV,-0.455853,-0.455661,-0.601476,-0.172615,0.015469,-0.664202,0.389056
5,BOU,-0.144830,-0.289859,0.053885,0.133285,-0.680638,0.535877,0.065380
6,SUN,0.237751,0.414259,0.942263,0.439184,-0.371257,0.785399,-0.407933
7,BHA,-0.468571,-0.653142,-0.499531,-0.522214,-0.603293,-0.248333,0.499181
8,BRE,0.106170,-0.191420,0.417975,0.133285,0.015469,0.215064,-0.116090
9,CHE,-0.000292,0.238749,-0.892747,0.002185,0.324850,-0.414681,0.123656
10,FUL,0.292110,0.383650,-0.353895,-0.391114,0.866267,0.013070,-0.135015
11,NEW,-0.086674,-0.132999,-0.062623,0.526584,-0.371257,0.203182,-0.012702
12,EVE,0.201059,0.281479,0.811191,-0.216315,0.634231,-0.022576,-0.281512
13,LEE,-0.192436,-0.343283,0.024758,0.045885,-0.680638,-0.414681,0.260066
14,CRY,0.206568,0.012844,-0.426713,0.089585,0.479541,-0.212687,-0.024856
15,NFO,0.709934,0.669292,0.476229,0.133285,0.479541,0.547759,-0.502673
16,TOT,-0.271261,-0.156919,-0.120878,-0.172615,-0.525948,-0.343389,0.265168
17,WHU,1.072067,0.984049,1.335480,1.444282,0.711577,1.415143,-1.160433
18,BUR,2.623752,2.633635,2.340366,2.274580,2.258482,2.068652,-2.366578
19,WOL,1.092214,1.189871,0.782064,0.919883,1.407684,1.165622,-1.092889

In [55]:
test_df = pd.merge(result, att_z_scores, how='left', on='team')
test_df = pd.merge(test_df, def_z_scores, how='left', on='team')
test_df = test_df.dropna()


test_df['att_strength'] = (league_elo_mean + 60 * test_df['elo_z'] + 40 * test_df['attMetric_z']).round().astype(int)
test_df['def_strength'] = (league_elo_mean + 60 * test_df['elo_z'] + 40 * test_df['defMetric_z']).round().astype(int)
display(test_df[['team', 'attMetric_z', 'defMetric_z', 'elo_preseason','att_strength', 'def_strength' ]].sort_values(['att_strength'], ascending=False).reset_index(drop=True))

   team  attMetric_z  defMetric_z  elo_preseason  att_strength  def_strength
0   ARS     1.345523     2.626586           2064          2001          2052
1   MCI     1.957382     1.313994           1971          1977          1951
2   MUN     1.293873     0.620581           1915          1921          1894
3   LIV     1.303585     0.389056           1911          1919          1883
4   AVL     0.208854    -0.062987           1921          1881          1870
5   BOU     0.304727     0.065380           1872          1859          1849
6   CHE     0.625288     0.123656           1831          1850          1830
7   BHA     0.196727     0.499181           1842          1839          1851
8   NEW     0.165739    -0.012702           1838          1836          1829
9   BRE     0.033852    -0.116090           1837          1830          1824
10  NFO    -0.361645    -0.502673           1822          1806          1801
11  CRY    -0.312321    -0.024856           1804          1799          1810
12  LEE    -0.279921     0.260066           1797          1797          1818
13  FUL    -0.497414    -0.135015           1813          1796          1811
14  EVE    -0.547556    -0.281512           1803          1789          1800
15  TOT    -0.517922     0.265168           1777          1777          1808
16  SUN    -1.138667    -0.407933           1736          1730          1760

In [56]:


# ============================================================
# 1. Generic helpers
# ============================================================

def compute_per_match(df: pd.DataFrame, columns: list[str]) -> pd.DataFrame:
    """
    Convert aggregate team statistics into per-match rates.

    Keeps team_id as the authoritative merge key and team as
    a human-readable label.
    """
    out = df.copy()

    # Avoid division by zero.
    matches = pd.to_numeric(out["matches_covered"], errors="coerce")
    matches = matches.replace(0, np.nan)

    per_match = out[columns].apply(pd.to_numeric, errors="coerce").div(
        matches,
        axis=0,
    )

    per_match.columns = [f"{column}_pm" for column in columns]

    return pd.concat(
        [
            out[["team_id", "team"]].reset_index(drop=True),
            per_match.reset_index(drop=True),
        ],
        axis=1,
    )


def compute_z_scores(
    df: pd.DataFrame,
    columns: list[str],
) -> pd.DataFrame:
    """
    Standardize team metrics relative to the teams in the
    current comparison population.

    A score of:
        0   = league average
        +1  = one SD above average
        -1  = one SD below average
    """
    out = df[["team_id", "team"]].copy()

    for column in columns:
        values = pd.to_numeric(df[column], errors="coerce")

        # zscore returns NaN for constant columns, so handle them explicitly.
        if values.notna().sum() < 2 or values.std(ddof=0) == 0:
            out[f"{column}_z"] = 0.0
        else:
            out[f"{column}_z"] = zscore(
                values,
                nan_policy="omit",
            )

    return out


def mean_columns(df: pd.DataFrame, columns: list[str]) -> pd.Series:
    """
    Safely average several standardized metrics into
    one family score.
    """
    return df[columns].mean(axis=1)


# ============================================================
# 2. ATTACKING STRENGTH
# ============================================================

attack_raw_columns = [
    "np_xg",
    "shots_total",
    "shots_on_target",
    "big_chance_shots",
    "key_passes",
    "big_chances_created",
    "shot_creating_actions",
    "touches_penalty_area",
    "box_entries",
]

attack_pm = compute_per_match(
    team_attack_df,
    attack_raw_columns,
)

attack_pm_columns = [
    f"{column}_pm"
    for column in attack_raw_columns
]


# Correlation should be inspected AFTER exposure normalization,
# not on the original aggregate totals.
attack_corr = attack_pm[attack_pm_columns].corr(
    method="spearman"
)


attack_z = compute_z_scores(
    attack_pm,
    attack_pm_columns,
)


# ------------------------------------------------------------
# Construct football-concept families.
#
# This avoids giving "shot generation" five votes simply
# because several highly related shot metrics are available.
# ------------------------------------------------------------

attack_z["chance_quality_z"] = attack_z["np_xg_pm_z"]

attack_z["shooting_threat_z"] = mean_columns(
    attack_z,
    [
        "shots_total_pm_z",
        "shots_on_target_pm_z",
        "big_chance_shots_pm_z",
    ],
)

attack_z["creation_z"] = mean_columns(
    attack_z,
    [
        "key_passes_pm_z",
        "big_chances_created_pm_z",
        "shot_creating_actions_pm_z",
    ],
)

attack_z["territory_z"] = mean_columns(
    attack_z,
    [
        "touches_penalty_area_pm_z",
        "box_entries_pm_z",
    ],
)


# Equal FAMILY weighting for the prototype.
#
# These are intentionally not claimed to be final weights.
# Later they should be validated against FUTURE attacking
# performance.
attack_z["attMetric_z"] = mean_columns(
    attack_z,
    [
        "chance_quality_z",
        "shooting_threat_z",
        "creation_z",
        "territory_z",
    ],
)


# ============================================================
# 3. DEFENSIVE STRENGTH
# ============================================================

defense_raw_columns = [
    "np_xga",
    "shots_conceded",
    "shots_on_target_against",
    "big_chances_conceded",
    "box_entries_against",
]

defense_pm = compute_per_match(
    team_def_df,
    defense_raw_columns,
)

defense_pm_columns = [
    f"{column}_pm"
    for column in defense_raw_columns
]


defense_corr = defense_pm[defense_pm_columns].corr(
    method="spearman"
)


defense_z = compute_z_scores(
    defense_pm,
    defense_pm_columns,
)


# These metrics are "lower is better".
#
# Negating them here means every family follows the same
# convention:
#
#     positive = stronger defence
#     negative = weaker defence
#
defense_z["chance_prevention_z"] = -defense_z["np_xga_pm_z"]

defense_z["shot_suppression_z"] = -mean_columns(
    defense_z,
    [
        "shots_conceded_pm_z",
        "shots_on_target_against_pm_z",
    ],
)

defense_z["big_chance_prevention_z"] = (
    -defense_z["big_chances_conceded_pm_z"]
)

defense_z["territory_prevention_z"] = (
    -defense_z["box_entries_against_pm_z"]
)


defense_z["defMetric_z"] = mean_columns(
    defense_z,
    [
        "chance_prevention_z",
        "shot_suppression_z",
        "big_chance_prevention_z",
        "territory_prevention_z",
    ],
)


# ============================================================
# 4. COMBINE WITH PRESEASON OVERALL ELO
# ============================================================

strength_df = (
    result
    .merge(
        attack_z[
            [
                "team_id",
                "attMetric_z",
            ]
        ],
        how="left",
        on="team_id",
        validate="one_to_one",
    )
    .merge(
        defense_z[
            [
                "team_id",
                "defMetric_z",
            ]
        ],
        how="left",
        on="team_id",
        validate="one_to_one",
    )
)


# ============================================================
# 5. DON'T SILENTLY DROP MISSING TEAMS
# ============================================================

missing_strength = strength_df[
    strength_df[
        [
            "elo_z",
            "attMetric_z",
            "defMetric_z",
        ]
    ].isna().any(axis=1)
].copy()

if not missing_strength.empty:
    print("Teams missing strength inputs:")
    print(
        missing_strength[
            [
                "team_id",
                "team",
                "elo_preseason",
                "elo_z",
                "attMetric_z",
                "defMetric_z",
            ]
        ]
    )


# Keep complete rows for the current experiment,
# but now missing teams are explicit rather than hidden.
complete = strength_df.dropna(
    subset=[
        "elo_z",
        "attMetric_z",
        "defMetric_z",
    ]
).copy()


# ============================================================
# 6. CURRENT PROTOTYPE RATING
# ============================================================
#
# IMPORTANT:
#
# 60 and 40 are Elo-scale point contributions per
# standard deviation. They are NOT literally 60% / 40%.
#
# Their values should eventually be learned or selected
# through chronological backtesting.
#

ELO_Z_POINTS = 60
METRIC_Z_POINTS = 40


complete["att_strength"] = (
    league_elo_mean
    + ELO_Z_POINTS * complete["elo_z"]
    + METRIC_Z_POINTS * complete["attMetric_z"]
).round()

complete["def_strength"] = (
    league_elo_mean
    + ELO_Z_POINTS * complete["elo_z"]
    + METRIC_Z_POINTS * complete["defMetric_z"]
).round()


# ============================================================
# 7. DISPLAY
# ============================================================

display_columns = [
    "team",
    "attMetric_z",
    "defMetric_z",
    "elo_preseason",
    "att_strength",
    "def_strength",
]

display(
    complete[
        display_columns
    ]
    .sort_values(
        "att_strength",
        ascending=False,
    )
    .reset_index(drop=True)
)

Teams missing strength inputs:
         team_id team  elo_preseason     elo_z  attMetric_z  defMetric_z
6   ce4d980327c7  COV           1661 -1.379111          NaN          NaN
10      c882a163  HUL           1533 -2.493544          NaN          NaN
11      53548284  IPS           1640 -1.561948          NaN          NaN

   team  attMetric_z  defMetric_z  elo_preseason  att_strength  def_strength
0   ARS     1.358692     2.603299           2064        2002.0        2051.0
1   MCI     1.962002     1.303931           1971        1977.0        1951.0
2   LIV     1.368232     0.372860           1911        1922.0        1882.0
3   MUN     1.227988     0.571127           1915        1918.0        1892.0
4   AVL     0.192227    -0.073211           1921        1880.0        1870.0
5   BOU     0.319842     0.085259           1872        1860.0        1850.0
6   CHE     0.630458     0.074091           1831        1851.0        1828.0
7   BHA     0.221625     0.503910           1842        1840.0        1851.0
8   NEW     0.187337     0.017274           1838        1837.0        1830.0
9   BRE     0.036743    -0.078686           1837        1830.0        1825.0
10  NFO    -0.419331    -0.500337           1822        1804.0        1801.0
11  CRY    -0.231273    -0.027783           1804        1802.0        1810.0
12  FUL    -0.444767    -0.222621           1813        1798.0        1807.0
13  LEE    -0.231163     0.350820           1797        1798.0        1822.0
14  EVE    -0.564346    -0.297643           1803        1788.0        1799.0
15  TOT    -0.551585     0.293251           1777        1775.0        1809.0
16  SUN    -1.173963    -0.379781           1736        1729.0        1761.0

In [57]:
archetypes = pd.read_csv('../data/processed/archetypes/model_version=1.0.0/snapshot=2026-08-18T06-57-49Z/archetypes.csv')


display(archetypes.describe())
display(archetypes.columns)
print(archetypes['archetype_id'].unique())

goal_threats = archetypes[archetypes['archetype_id'].eq('GOAL_THREAT') & archetypes['active_label'].eq(True) & archetypes['fpl_position'].eq('FWD')].reset_index(drop=True)
print(goal_threats['player_name'].unique())
#display(goal_threats)

def display_archetype_by_pos(df, archetype, position):
    df = df.copy()

    archetype_df = df[df['archetype_id'].eq(archetype) & df['active_label'].eq(True) & df['fpl_position'].eq(position)].reset_index(drop=True)

    return archetype_df

archs = ['GOAL_THREAT', 'DEFENSIVE_ENGINE']

for pos, label in [('MID', 'Midfielders'), ('DEF', 'Defenders'), ('FWD', 'Forwards')]:
    for arch in archs:
        archetype_df = display_archetype_by_pos(archetypes, arch, pos)
        display(f"{label} - {arch} score:", archetype_df.sort_values("score_0_100", ascending=False).reset_index(drop=True))

,score_0_100,confidence_0_1,evidence_minutes,eligible_appearances,below_exit_updates,trend_persistence,pending_usage_state,pending_usage_updates
count,7272.000000,7906.000000,7906.000000,7906.000000,7746.00000,7746.000000,0.0,481.0
mean,50.402554,0.506898,1813.956868,18.985201,0.00142,3.391428,NaN,0.0
std,28.452914,0.248575,1662.371514,18.471173,0.03766,1.204639,NaN,0.0
min,0.000000,0.000000,0.000000,0.000000,0.00000,1.000000,NaN,0.0
25%,25.475000,0.353469,336.000000,3.000000,0.00000,4.000000,NaN,0.0
50%,50.400000,0.584375,1461.000000,15.000000,0.00000,4.000000,NaN,0.0
75%,75.300000,0.750000,2883.500000,31.000000,0.00000,4.000000,NaN,0.0
max,100.000000,0.750000,6840.000000,76.000000,1.00000,4.000000,NaN,0.0

Index(['player_id', 'player_name', 'snapshot_date', 'fpl_position',
       'archetype_id', 'display_name', 'family', 'score_0_100', 'active_label',
       'confidence_0_1', 'confidence_band', 'trend', 'status',
       'evidence_minutes', 'eligible_appearances', 'component_scores',
       'missing_data_flags', 'below_exit_updates', 'trend_direction',
       'trend_persistence', 'model_version', 'pending_usage_state',
       'pending_usage_updates', 'transition_applied'],
      dtype='str')

<ArrowStringArray>
[            'ANYWHERE_THREAT',   'BENCH_AUTOFILL_HISTORICAL',
                     'CREATOR',            'DEFENSIVE_ENGINE',
          'EXPLOSIVE_RETURNER',               'FODDER_HUNTER',
                 'GOAL_THREAT',       'HIDDEN_GEM_HISTORICAL',
 'HIGH_MAINTENANCE_HISTORICAL',               'HOME_FAVORITE',
               'MATCHUP_PROOF',               'POINTS_HAZARD',
     'PREMIUM_PICK_HISTORICAL',           'PRODSTYLE_MID_G_C',
                'ROAD_WARRIOR',               'ROTATION_RISK',
             'STEADY_RETURNER',                      'FRINGE',
             'PRODSTYLE_MID_D',      'CLEAN_SHEET_SPECIALIST',
           'PRODSTYLE_DEF_G_C',             'PRODSTYLE_DEF_G',
             'PRODSTYLE_MID_C',                  'IMPACT_SUB',
             'REGULAR_STARTER',           'PRODSTYLE_DEF_G_D',
           'PRODSTYLE_DEF_C_D',             'PRODSTYLE_DEF_C',
               'SAVES_MACHINE',           'PRODSTYLE_FWD_G_D',
           'PRODSTYLE_MID_C_D',         'PRODSTYLE_DEF_G_C_D',
             'PRODSTYLE_GKP_S',             'PRODSTYLE_MID_G',
             'PRODSTYLE_DEF_D',           'PRODSTYLE_FWD_C_D',
           'PRODSTYLE_FWD_G_C',             'PRODSTYLE_FWD_C',
             'PRODSTYLE_FWD_G',           'PRODSTYLE_MID_G_D',
             'PRODSTYLE_FWD_D']
Length: 41, dtype: str
<ArrowStringArray>
[               'Thiago',          'Hugo Ekitike',                  'Beto',
        'Erling Haaland',        'Benjamin Šeško',         'Ollie Watkins',
           'Kai Havertz', 'Dominic Calvert-Lewin']
Length: 8, dtype: str

'Midfielders - GOAL_THREAT score:'

,player_id,player_name,snapshot_date,fpl_position,archetype_id,display_name,family,score_0_100,active_label,confidence_0_1,confidence_band,trend,status,evidence_minutes,eligible_appearances,component_scores,missing_data_flags,below_exit_updates,trend_direction,trend_persistence,model_version,pending_usage_state,pending_usage_updates,transition_applied
0,29f66656,Bryan Mbeumo,2026-08-18T06:57:49.693935+00:00,MID,GOAL_THREAT,Goal Threat,Production Style,100.00,True,0.711162,Medium,Stable,Provisional,2576,31,"{""window_weights"":{""earlier_current"":0.0,""prev...",[],0.0,stable,4.0,1.0.0,NaN,NaN,NaN
1,5c02cb8e,Cole Palmer,2026-08-18T06:57:49.693935+00:00,MID,GOAL_THREAT,Goal Threat,Production Style,99.40,True,0.701872,Medium,Stable,Provisional,1905,24,"{""window_weights"":{""earlier_current"":0.0,""prev...",[],0.0,stable,4.0,1.0.0,NaN,NaN,NaN
2,77ba57bf,Antoine Semenyo,2026-08-18T06:57:49.693935+00:00,MID,GOAL_THREAT,Goal Threat,Production Style,98.80,True,0.717074,Medium,Stable,Provisional,3200,37,"{""window_weights"":{""earlier_current"":0.0,""prev...",[],0.0,stable,4.0,1.0.0,NaN,NaN,NaN
3,ca30122f,Ismaïla Sarr,2026-08-18T06:57:49.693935+00:00,MID,GOAL_THREAT,Goal Threat,Production Style,98.30,True,0.705695,Medium,Stable,Provisional,2147,27,"{""window_weights"":{""earlier_current"":0.0,""prev...",[],0.0,stable,4.0,1.0.0,NaN,NaN,NaN
4,c61c1467,Morgan Gibbs-White,2026-08-18T06:57:49.693935+00:00,MID,GOAL_THREAT,Goal Threat,Production Style,97.70,True,0.716089,Medium,Stable,Provisional,3081,36,"{""window_weights"":{""earlier_current"":0.0,""prev...",[],0.0,stable,4.0,1.0.0,NaN,NaN,NaN
5,a26b9783,Eli Junior Kroupi,2026-08-18T06:57:49.693935+00:00,MID,GOAL_THREAT,Goal Threat,Production Style,97.10,True,0.555335,Medium,Stable,Provisional,1518,22,"{""window_weights"":{""earlier_current"":0.0,""prev...",[],0.0,stable,4.0,1.0.0,NaN,NaN,NaN
6,612cce56,Kevin Schade,2026-08-18T06:57:49.693935+00:00,MID,GOAL_THREAT,Goal Threat,Production Style,96.50,True,0.712248,Medium,Stable,Provisional,2676,33,"{""window_weights"":{""earlier_current"":0.0,""prev...",[],0.0,stable,4.0,1.0.0,NaN,NaN,NaN
7,3298e248,Noah Okafor,2026-08-18T06:57:49.693935+00:00,MID,GOAL_THREAT,Goal Threat,Production Style,96.00,True,0.692357,Medium,Stable,Provisional,1442,21,"{""window_weights"":{""earlier_current"":0.0,""prev...",[],0.0,stable,4.0,1.0.0,NaN,NaN,NaN
8,c00b591b,Bukayo Saka,2026-08-18T06:57:49.693935+00:00,MID,GOAL_THREAT,Goal Threat,Production Style,95.40,True,0.705548,Medium,Stable,Provisional,2137,27,"{""window_weights"":{""earlier_current"":0.0,""prev...",[],0.0,stable,4.0,1.0.0,NaN,NaN,NaN
9,4ff037a3,Enzo Fernández,2026-08-18T06:57:49.693935+00:00,MID,GOAL_THREAT,Goal Threat,Production Style,94.80,True,0.716368,Medium,Stable,Provisional,3114,36,"{""window_weights"":{""earlier_current"":0.0,""prev...",[],0.0,stable,4.0,1.0.0,NaN,NaN,NaN
10,1c34da7c,Dango Ouattara,2026-08-18T06:57:49.693935+00:00,MID,GOAL_THREAT,Goal Threat,Production Style,94.20,True,0.705868,Medium,Stable,Provisional,2159,26,"{""window_weights"":{""earlier_current"":0.0,""prev...",[],0.0,stable,4.0,1.0.0,NaN,NaN,NaN
11,2c676f84,Matheus Cunha,2026-08-18T06:57:49.693935+00:00,MID,GOAL_THREAT,Goal Threat,Production Style,93.60,True,0.709116,Medium,Stable,Provisional,2402,29,"{""window_weights"":{""earlier_current"":0.0,""prev...",[],0.0,stable,4.0,1.0.0,NaN,NaN,NaN
12,0c0888ab,Bruno Fernandes,2026-08-18T06:57:49.693935+00:00,MID,GOAL_THREAT,Goal Threat,Production Style,93.10,True,0.715952,Medium,Stable,Provisional,3065,35,"{""window_weights"":{""earlier_current"":0.0,""prev...",[],0.0,stable,4.0,1.0.0,NaN,NaN,NaN
13,2b5a53c9,Cody Gakpo,2026-08-18T06:57:49.693935+00:00,MID,GOAL_THREAT,Goal Threat,Production Style,92.50,True,0.712583,Medium,Stable,Provisional,2708,34,"{""window_weights"":{""earlier_current"":0.0,""prev...",[],0.0,stable,4.0,1.0.0,NaN,NaN,NaN
14,d2b90140,Harvey Barnes,2026-08-18T06:57:49.693935+00:00,MID,GOAL_THREAT,Goal Threat,Production Style,91.90,True,0.696955,Medium,Stable,Provisional,1645,23,"{""window_weights"":{""earlier_current"":0.0,""prev...",[],0.0,stable,4.0,1.0.0,NaN,NaN,NaN
15,a888d251,David Brooks,2026-08-18T06:57:49.693935+00:00,MID,GOAL_THREAT,Goal Threat,Production Style,91.30,True,0.676909,Medium,Stable,Provisional,947,15,"{""window_weights"":{""earlier_current"":0.0,""prev...",[],0.0,stable,4.0,1.0.0,NaN,NaN,NaN
16,1be64912,Marcus Tavernier,2026-08-18T06:57:49.693935+00:00,MID,GOAL_THREAT,Goal Threat,Production Style,90.80,True,0.712728,Medium,Stable,Provisional,2722,33,"{""window_weights"":{""earlier_current"":0.0,""prev...",[],0.0,stable,4.0,1.0.0,NaN,NaN,NaN
17,00a05a27,Phil Foden,2026-08-18T06:57:49.693935+00:00,MID,GOAL_THREAT,Goal Threat,Production Style,90.20,True,0.703093,Medium,Stable,Provisional,1978,25,"{""window_weights"":{""earlier_current"":0.0,""prev...",[],0.0,stable,4.0,1.0.0,NaN,NaN,NaN
18,65c63664,Eberechi Eze,2026-08-18T06:57:49.693935+00:00,MID,GOAL_THREAT,Goal Threat,Production Style,89.60,True,0.698883,Medium,Stable,Provisional,1741,25,"{""window_weights"":{""earlier_current"":0.0,""prev...",[],0.0,stable,4.0,1.0.0,NaN,NaN,NaN
19,6a4da7e5,Mikel Merino,2026-08-18T06:57:49.693935+00:00,MID,GOAL_THREAT,Goal Threat,Production Style,89.00,True,0.675414,Medium,Stable,Provisional,910,14,"{""window_weights"":{""earlier_current"":0.0,""prev...",[],0.0,stable,4.0,1.0.0,NaN,NaN,NaN
20,86111fa8,Florian Wirtz,2026-08-18T06:57:49.693935+00:00,MID,GOAL_THREAT,Goal Threat,Production Style,87.30,True,0.707319,Medium,Stable,Provisional,2263,28,"{""window_weights"":{""earlier_current"":0.0,""prev...",[],0.0,stable,4.0,1.0.0,NaN,NaN,NaN
21,9ec9e5ed,Amine Adli,2026-08-18T06:57:49.693935+00:00,MID,GOAL_THREAT,Goal Threat,Production Style,86.10,True,0.624377,Medium,Stable,Provisional,729,10,"{""window_weights"":{""earlier_current"":0.0,""prev...",[],0.0,stable,4.0,1.0.0,NaN,NaN,NaN
22,ac84f42c,Estêvão Willian,2026-08-18T06:57:49.693935+00:00,MID,GOAL_THREAT,Goal Threat,Production Style,85.50,True,0.615928,Medium,Stable,Provisional,701,12,"{""window_weights"":{""earlier_current"":0.0,""prev...",[],0.0,stable,4.0,1.0.0,NaN,NaN,NaN
23,47f3988a,Jack Hinshelwood,2026-08-18T06:57:49.693935+00:00,MID,GOAL_THREAT,Goal Threat,Production Style,85.00,True,0.697836,Medium,Stable,Provisional,1688,23,"{""window_weights"":{""earlier_current"":0.0,""prev...",[],0.0,stable,4.0,1.0.0,NaN,NaN,NaN
24,80472fd5,Tijjani Reijnders,2026-08-18T06:57:49.693935+00:00,MID,GOAL_THREAT,Goal Threat,Production Style,84.40,True,0.693773,Medium,Stable,Provisional,1501,20,"{""window_weights"":{""earlier_current"":0.0,""prev...",[],0.0,stable,4.0,1.0.0,NaN,NaN,NaN
25,a91bad3f,Jeremy Doku,2026-08-18T06:57:49.693935+00:00,MID,GOAL_THREAT,Goal Threat,Production Style,83.80,True,0.697059,Medium,Stable,Provisional,1650,23,"{""window_weights"":{""earlier_current"":0.0,""prev...",[],0.0,stable,4.0,1.0.0,NaN,NaN,NaN
26,b6f0558f,Gabriel Martinelli,2026-08-18T06:57:49.693935+00:00,MID,GOAL_THREAT,Goal Threat,Production Style,82.70,True,0.660063,Medium,Stable,Provisional,849,15,"{""window_weights"":{""earlier_current"":0.0,""prev...",[],0.0,stable,4.0,1.0.0,NaN,NaN,NaN
27,b5c236ab,Diego Gómez,2026-08-18T06:57:49.693935+00:00,MID,GOAL_THREAT,Goal Threat,Production Style,81.50,True,0.703608,Medium,Stable,Provisional,2010,27,"{""window_weights"":{""earlier_current"":0.0,""prev...",[],0.0,stable,4.0,1.0.0,NaN,NaN,NaN
28,463a677e,Rayan Cherki,2026-08-18T06:57:49.693935+00:00,MID,GOAL_THREAT,Goal Threat,Production Style,80.90,True,0.696788,Medium,Stable,Provisional,1637,24,"{""window_weights"":{""earlier_current"":0.0,""prev...",[],0.0,stable,4.0,1.0.0,NaN,NaN,NaN
29,af9c8a66,Harry Wilson,2026-08-18T06:57:49.693935+00:00,MID,GOAL_THREAT,Goal Threat,Production Style,80.72,True,0.533711,Low,Stable,Provisional,2617,33,"{""window_weights"":{""earlier_current"":0.0,""prev...",[],0.0,stable,4.0,1.0.0,NaN,NaN,NaN
30,d307d495,Bruno Guimarães,2026-08-18T06:57:49.693935+00:00,MID,GOAL_THREAT,Goal Threat,Production Style,80.32,True,0.532076,Low,Stable,Provisional,2428,28,"{""window_weights"":{""earlier_current"":0.0,""prev...",[],0.0,stable,4.0,1.0.0,NaN,NaN,NaN
31,b8ce561e,Amad Diallo,2026-08-18T06:57:49.693935+00:00,MID,GOAL_THREAT,Goal Threat,Production Style,78.00,True,0.707812,Medium,Stable,Established,2300,29,"{""window_weights"":{""earlier_current"":0.0,""prev...",[],0.0,stable,4.0,1.0.0,NaN,NaN,NaN

'Midfielders - DEFENSIVE_ENGINE score:'

,player_id,player_name,snapshot_date,fpl_position,archetype_id,display_name,family,score_0_100,active_label,confidence_0_1,confidence_band,trend,status,evidence_minutes,eligible_appearances,component_scores,missing_data_flags,below_exit_updates,trend_direction,trend_persistence,model_version,pending_usage_state,pending_usage_updates,transition_applied
0,8bcef49f,Rodrigo Bentancur,2026-08-18T06:57:49.693935+00:00,MID,DEFENSIVE_ENGINE,Defensive Engine,Production Style,99.40,True,0.700909,Medium,Stable,Provisional,1850,24,"{""window_weights"":{""earlier_current"":0.0,""prev...",[],0.0,stable,4.0,1.0.0,NaN,NaN,NaN
1,87cb7b87,James Garner,2026-08-18T06:57:49.693935+00:00,MID,DEFENSIVE_ENGINE,Defensive Engine,Production Style,98.90,True,0.718699,Medium,Stable,Provisional,3413,38,"{""window_weights"":{""earlier_current"":0.0,""prev...",[],0.0,stable,4.0,1.0.0,NaN,NaN,NaN
2,99355275,Ethan Ampadu,2026-08-18T06:57:49.693935+00:00,MID,DEFENSIVE_ENGINE,Defensive Engine,Production Style,97.70,True,0.716410,Medium,Stable,Provisional,3119,35,"{""window_weights"":{""earlier_current"":0.0,""prev...",[],0.0,stable,4.0,1.0.0,NaN,NaN,NaN
3,3bb5fbe3,Alex Scott,2026-08-18T06:57:49.693935+00:00,MID,DEFENSIVE_ENGINE,Defensive Engine,Production Style,97.10,True,0.713971,Medium,Stable,Provisional,2847,36,"{""window_weights"":{""earlier_current"":0.0,""prev...",[],0.0,stable,4.0,1.0.0,NaN,NaN,NaN
4,751ffedb,Yehor Yarmoliuk,2026-08-18T06:57:49.693935+00:00,MID,DEFENSIVE_ENGINE,Defensive Engine,Production Style,96.00,True,0.710971,Medium,Stable,Provisional,2559,32,"{""window_weights"":{""earlier_current"":0.0,""prev...",[],0.0,stable,4.0,1.0.0,NaN,NaN,NaN
5,bdf572d7,Rodri,2026-08-18T06:57:49.693935+00:00,MID,DEFENSIVE_ENGINE,Defensive Engine,Production Style,95.40,True,0.692479,Medium,Stable,Provisional,1447,17,"{""window_weights"":{""earlier_current"":0.0,""prev...",[],0.0,stable,4.0,1.0.0,NaN,NaN,NaN
6,d1f22421,Lewis Cook,2026-08-18T06:57:49.693935+00:00,MID,DEFENSIVE_ENGINE,Defensive Engine,Production Style,94.80,True,0.623919,Medium,Stable,Provisional,765,9,"{""window_weights"":{""earlier_current"":0.0,""prev...",[],0.0,stable,4.0,1.0.0,NaN,NaN,NaN
7,4c868f33,Tyler Adams,2026-08-18T06:57:49.693935+00:00,MID,DEFENSIVE_ENGINE,Defensive Engine,Production Style,93.70,True,0.698137,Medium,Stable,Provisional,1703,21,"{""window_weights"":{""earlier_current"":0.0,""prev...",[],0.0,stable,4.0,1.0.0,NaN,NaN,NaN
8,b2dc4c72,Patrick Dorgu,2026-08-18T06:57:49.693935+00:00,MID,DEFENSIVE_ENGINE,Defensive Engine,Production Style,93.10,True,0.550730,Medium,Stable,Provisional,1292,16,"{""window_weights"":{""earlier_current"":0.0,""prev...",[],0.0,stable,4.0,1.0.0,NaN,NaN,NaN
9,7d260201,Pape Matar Sarr,2026-08-18T06:57:49.693935+00:00,MID,DEFENSIVE_ENGINE,Defensive Engine,Production Style,92.50,True,0.686560,Medium,Stable,Provisional,1228,15,"{""window_weights"":{""earlier_current"":0.0,""prev...",[],0.0,stable,4.0,1.0.0,NaN,NaN,NaN
10,b94b9100,Moisés Caicedo,2026-08-18T06:57:49.693935+00:00,MID,DEFENSIVE_ENGINE,Defensive Engine,Production Style,92.00,True,0.713105,Medium,Stable,Provisional,2759,32,"{""window_weights"":{""earlier_current"":0.0,""prev...",[],0.0,stable,4.0,1.0.0,NaN,NaN,NaN
11,3164299a,Nicolás González,2026-08-18T06:57:49.693935+00:00,MID,DEFENSIVE_ENGINE,Defensive Engine,Production Style,91.40,True,0.692258,Medium,Stable,Provisional,1438,18,"{""window_weights"":{""earlier_current"":0.0,""prev...",[],0.0,stable,4.0,1.0.0,NaN,NaN,NaN
12,476e6d8a,Granit Xhaka,2026-08-18T06:57:49.693935+00:00,MID,DEFENSIVE_ENGINE,Defensive Engine,Production Style,90.80,True,0.714305,Medium,Stable,Provisional,2882,33,"{""window_weights"":{""earlier_current"":0.0,""prev...",[],0.0,stable,4.0,1.0.0,NaN,NaN,NaN
13,24126a56,Ibrahim Sangaré,2026-08-18T06:57:49.693935+00:00,MID,DEFENSIVE_ENGINE,Defensive Engine,Production Style,90.20,True,0.704050,Medium,Stable,Provisional,2038,25,"{""window_weights"":{""earlier_current"":0.0,""prev...",[],0.0,stable,4.0,1.0.0,NaN,NaN,NaN
14,683b923f,Elliot Anderson,2026-08-18T06:57:49.693935+00:00,MID,DEFENSIVE_ENGINE,Defensive Engine,Production Style,90.00,True,0.538575,Low,Stable,Provisional,3332,38,"{""window_weights"":{""earlier_current"":0.0,""prev...",[],0.0,stable,4.0,1.0.0,NaN,NaN,NaN
15,59424615,Declan Rice,2026-08-18T06:57:49.693935+00:00,MID,DEFENSIVE_ENGINE,Defensive Engine,Production Style,89.70,True,0.716003,Medium,Stable,Provisional,3071,35,"{""window_weights"":{""earlier_current"":0.0,""prev...",[],0.0,stable,4.0,1.0.0,NaN,NaN,NaN
16,3c41849c,Adam Wharton,2026-08-18T06:57:49.693935+00:00,MID,DEFENSIVE_ENGINE,Defensive Engine,Production Style,89.10,True,0.709556,Medium,Stable,Provisional,2438,31,"{""window_weights"":{""earlier_current"":0.0,""prev...",[],0.0,stable,4.0,1.0.0,NaN,NaN,NaN
17,97bd77db,Florentino Luís,2026-08-18T06:57:49.693935+00:00,MID,DEFENSIVE_ENGINE,Defensive Engine,Production Style,88.64,True,0.527849,Low,Stable,Provisional,2022,26,"{""window_weights"":{""earlier_current"":0.0,""prev...",[],0.0,stable,4.0,1.0.0,NaN,NaN,NaN
18,a1f6d17c,Amadou Onana,2026-08-18T06:57:49.693935+00:00,MID,DEFENSIVE_ENGINE,Defensive Engine,Production Style,88.50,True,0.698512,Medium,Stable,Provisional,1722,22,"{""window_weights"":{""earlier_current"":0.0,""prev...",[],0.0,stable,4.0,1.0.0,NaN,NaN,NaN
19,12137356,Joelinton,2026-08-18T06:57:49.693935+00:00,MID,DEFENSIVE_ENGINE,Defensive Engine,Production Style,87.90,True,0.701193,Medium,Stable,Provisional,1866,23,"{""window_weights"":{""earlier_current"":0.0,""prev...",[],0.0,stable,4.0,1.0.0,NaN,NaN,NaN
20,01757724,Manuel Ugarte Ribeiro,2026-08-18T06:57:49.693935+00:00,MID,DEFENSIVE_ENGINE,Defensive Engine,Production Style,87.40,True,0.621667,Medium,Stable,Provisional,720,10,"{""window_weights"":{""earlier_current"":0.0,""prev...",[],0.0,stable,4.0,1.0.0,NaN,NaN,NaN
21,c2210749,João Gomes,2026-08-18T06:57:49.693935+00:00,MID,DEFENSIVE_ENGINE,Defensive Engine,Production Style,87.28,True,0.535165,Low,Stable,Provisional,2804,33,"{""window_weights"":{""earlier_current"":0.0,""prev...",[],0.0,stable,4.0,1.0.0,NaN,NaN,NaN
22,b5c236ab,Diego Gómez,2026-08-18T06:57:49.693935+00:00,MID,DEFENSIVE_ENGINE,Defensive Engine,Production Style,86.80,True,0.703608,Medium,Stable,Provisional,2010,27,"{""window_weights"":{""earlier_current"":0.0,""prev...",[],0.0,stable,4.0,1.0.0,NaN,NaN,NaN
23,12e86930,Anton Stach,2026-08-18T06:57:49.693935+00:00,MID,DEFENSIVE_ENGINE,Defensive Engine,Production Style,86.20,True,0.708423,Medium,Stable,Provisional,2347,28,"{""window_weights"":{""earlier_current"":0.0,""prev...",[],0.0,stable,4.0,1.0.0,NaN,NaN,NaN
24,84cee7da,Lewis Miley,2026-08-18T06:57:49.693935+00:00,MID,DEFENSIVE_ENGINE,Defensive Engine,Production Style,85.60,True,0.691558,Medium,Stable,Provisional,1410,17,"{""window_weights"":{""earlier_current"":0.0,""prev...",[],0.0,stable,4.0,1.0.0,NaN,NaN,NaN
25,604741e3,Mateus Fernandes,2026-08-18T06:57:49.693935+00:00,MID,DEFENSIVE_ENGINE,Defensive Engine,Production Style,85.44,True,0.536485,Low,Stable,Provisional,2992,35,"{""window_weights"":{""earlier_current"":0.0,""prev...",[],0.0,stable,4.0,1.0.0,NaN,NaN,NaN
26,d642e423,Mikkel Damsgaard,2026-08-18T06:57:49.693935+00:00,MID,DEFENSIVE_ENGINE,Defensive Engine,Production Style,85.10,True,0.701264,Medium,Stable,Provisional,1870,24,"{""window_weights"":{""earlier_current"":0.0,""prev...",[],0.0,stable,4.0,1.0.0,NaN,NaN,NaN
27,9e517f78,Curtis Jones,2026-08-18T06:57:49.693935+00:00,MID,DEFENSIVE_ENGINE,Defensive Engine,Production Style,84.50,True,0.697796,Medium,Stable,Provisional,1686,22,"{""window_weights"":{""earlier_current"":0.0,""prev...",[],0.0,stable,4.0,1.0.0,NaN,NaN,NaN
28,3d84315e,Tim Iroegbunam,2026-08-18T06:57:49.693935+00:00,MID,DEFENSIVE_ENGINE,Defensive Engine,Production Style,83.90,True,0.689732,Medium,Stable,Provisional,1340,17,"{""window_weights"":{""earlier_current"":0.0,""prev...",[],0.0,stable,4.0,1.0.0,NaN,NaN,NaN
29,c4229c47,Vitaly Janelt,2026-08-18T06:57:49.693935+00:00,MID,DEFENSIVE_ENGINE,Defensive Engine,Production Style,82.80,True,0.688553,Medium,Stable,Provisional,1297,16,"{""window_weights"":{""earlier_current"":0.0,""prev...",[],0.0,stable,4.0,1.0.0,NaN,NaN,NaN
30,51f20c6c,Enzo Le Fée,2026-08-18T06:57:49.693935+00:00,MID,DEFENSIVE_ENGINE,Defensive Engine,Production Style,82.20,True,0.714323,Medium,Stable,Provisional,2884,33,"{""window_weights"":{""earlier_current"":0.0,""prev...",[],0.0,stable,4.0,1.0.0,NaN,NaN,NaN
31,59581b91,Dominik Szoboszlai,2026-08-18T06:57:49.693935+00:00,MID,DEFENSIVE_ENGINE,Defensive Engine,Production Style,81.60,True,0.716601,Medium,Stable,Provisional,3142,35,"{""window_weights"":{""earlier_current"":0.0,""prev...",[],0.0,stable,4.0,1.0.0,NaN,NaN,NaN
32,808a57c7,Conor Gallagher,2026-08-18T06:57:49.693935+00:00,MID,DEFENSIVE_ENGINE,Defensive Engine,Production Style,81.00,True,0.685003,Medium,Stable,Provisional,1177,15,"{""window_weights"":{""earlier_current"":0.0,""prev...",[],0.0,stable,4.0,1.0.0,NaN,NaN,NaN
33,e53698b5,Carlos Baleba,2026-08-18T06:57:49.693935+00:00,MID,DEFENSIVE_ENGINE,Defensive Engine,Production Style,80.50,True,0.694604,Medium,Stable,Provisional,1537,23,"{""window_weights"":{""earlier_current"":0.0,""prev...",[],0.0,stable,4.0,1.0.0,NaN,NaN,NaN

'Defenders - GOAL_THREAT score:'

,player_id,player_name,snapshot_date,fpl_position,archetype_id,display_name,family,score_0_100,active_label,confidence_0_1,confidence_band,trend,status,evidence_minutes,eligible_appearances,component_scores,missing_data_flags,below_exit_updates,trend_direction,trend_persistence,model_version,pending_usage_state,pending_usage_updates,transition_applied
0,397dac19,Nico O’Reilly,2026-08-18T06:57:49.693935+00:00,DEF,GOAL_THREAT,Goal Threat,Production Style,100.0,True,0.710927,Medium,Stable,Provisional,2555,30,"{""window_weights"":{""earlier_current"":0.0,""prev...",[],0.0,stable,4.0,1.0.0,NaN,NaN,NaN
1,37038cd7,Malick Thiaw,2026-08-18T06:57:49.693935+00:00,DEF,GOAL_THREAT,Goal Threat,Production Style,99.2,True,0.714971,Medium,Stable,Provisional,2954,34,"{""window_weights"":{""earlier_current"":0.0,""prev...",[],0.0,stable,4.0,1.0.0,NaN,NaN,NaN
2,322d5e0f,Daniel Muñoz,2026-08-18T06:57:49.693935+00:00,DEF,GOAL_THREAT,Goal Threat,Production Style,98.4,True,0.708929,Medium,Stable,Provisional,2387,28,"{""window_weights"":{""earlier_current"":0.0,""prev...",[],0.0,stable,4.0,1.0.0,NaN,NaN,NaN
3,d614da42,Virgil van Dijk,2026-08-18T06:57:49.693935+00:00,DEF,GOAL_THREAT,Goal Threat,Production Style,97.6,True,0.718750,Medium,Stable,Provisional,3420,38,"{""window_weights"":{""earlier_current"":0.0,""prev...",[],0.0,stable,4.0,1.0.0,NaN,NaN,NaN
4,1a73ad96,Riccardo Calafiori,2026-08-18T06:57:49.693935+00:00,DEF,GOAL_THREAT,Goal Threat,Production Style,96.9,True,0.696976,Medium,Stable,Provisional,1646,22,"{""window_weights"":{""earlier_current"":0.0,""prev...",[],0.0,stable,4.0,1.0.0,NaN,NaN,NaN
5,9ae96ab6,Daniel Ballard,2026-08-18T06:57:49.693935+00:00,DEF,GOAL_THREAT,Goal Threat,Production Style,96.1,True,0.704191,Medium,Stable,Provisional,2047,24,"{""window_weights"":{""earlier_current"":0.0,""prev...",[],0.0,stable,4.0,1.0.0,NaN,NaN,NaN
6,8be75f47,Jurriën Timber,2026-08-18T06:57:49.693935+00:00,DEF,GOAL_THREAT,Goal Threat,Production Style,95.3,True,0.709496,Medium,Stable,Provisional,2433,29,"{""window_weights"":{""earlier_current"":0.0,""prev...",[],0.0,stable,4.0,1.0.0,NaN,NaN,NaN
7,313c9b46,Joško Gvardiol,2026-08-18T06:57:49.693935+00:00,DEF,GOAL_THREAT,Goal Threat,Production Style,94.5,True,0.690212,Medium,Stable,Provisional,1358,17,"{""window_weights"":{""earlier_current"":0.0,""prev...",[],0.0,stable,4.0,1.0.0,NaN,NaN,NaN
8,20f73533,Cristian Romero,2026-08-18T06:57:49.693935+00:00,DEF,GOAL_THREAT,Goal Threat,Production Style,93.7,True,0.699076,Medium,Stable,Provisional,1751,21,"{""window_weights"":{""earlier_current"":0.0,""prev...",[],0.0,stable,4.0,1.0.0,NaN,NaN,NaN
9,56bd61e6,Marc Guéhi,2026-08-18T06:57:49.693935+00:00,DEF,GOAL_THREAT,Goal Threat,Production Style,92.9,True,0.716667,Medium,Stable,Provisional,3150,35,"{""window_weights"":{""earlier_current"":0.0,""prev...",[],0.0,stable,4.0,1.0.0,NaN,NaN,NaN
10,3213dc02,James Justin,2026-08-18T06:57:49.693935+00:00,DEF,GOAL_THREAT,Goal Threat,Production Style,92.1,True,0.700874,Medium,Stable,Provisional,1848,22,"{""window_weights"":{""earlier_current"":0.0,""prev...",[],0.0,stable,4.0,1.0.0,NaN,NaN,NaN
11,0618feac,Ryan Sessegnon,2026-08-18T06:57:49.693935+00:00,DEF,GOAL_THREAT,Goal Threat,Production Style,91.3,True,0.558794,Medium,Stable,Provisional,1721,21,"{""window_weights"":{""earlier_current"":0.0,""prev...",[],0.0,stable,4.0,1.0.0,NaN,NaN,NaN
12,4312b1e6,Nicolò Savona,2026-08-18T06:57:49.693935+00:00,DEF,GOAL_THREAT,Goal Threat,Production Style,89.8,True,0.678496,Medium,Stable,Provisional,988,12,"{""window_weights"":{""earlier_current"":0.0,""prev...",[],0.0,stable,4.0,1.0.0,NaN,NaN,NaN
13,b26765e2,Neco Williams,2026-08-18T06:57:49.693935+00:00,DEF,GOAL_THREAT,Goal Threat,Production Style,88.2,True,0.716741,Medium,Stable,Provisional,3159,36,"{""window_weights"":{""earlier_current"":0.0,""prev...",[],0.0,stable,4.0,1.0.0,NaN,NaN,NaN
14,bef4a612,Mats Wieffer,2026-08-18T06:57:49.693935+00:00,DEF,GOAL_THREAT,Goal Threat,Production Style,87.4,True,0.561137,Medium,Stable,Provisional,1879,24,"{""window_weights"":{""earlier_current"":0.0,""prev...",[],0.0,stable,4.0,1.0.0,NaN,NaN,NaN
15,15b06139,Nordi Mukiele,2026-08-18T06:57:49.693935+00:00,DEF,GOAL_THREAT,Goal Threat,Production Style,86.6,True,0.713245,Medium,Stable,Provisional,2773,31,"{""window_weights"":{""earlier_current"":0.0,""prev...",[],0.0,stable,4.0,1.0.0,NaN,NaN,NaN
16,dcfd6f9f,Matthijs de Ligt,2026-08-18T06:57:49.693935+00:00,DEF,GOAL_THREAT,Goal Threat,Production Style,85.8,True,0.684782,Medium,Stable,Provisional,1170,13,"{""window_weights"":{""earlier_current"":0.0,""prev...",[],0.0,stable,4.0,1.0.0,NaN,NaN,NaN
17,09f73256,Michael Keane,2026-08-18T06:57:49.693935+00:00,DEF,GOAL_THREAT,Goal Threat,Production Style,85.0,True,0.710224,Medium,Stable,Provisional,2494,28,"{""window_weights"":{""earlier_current"":0.0,""prev...",[],0.0,stable,4.0,1.0.0,NaN,NaN,NaN
18,c2a732e0,Joshua Acheampong,2026-08-18T06:57:49.693935+00:00,DEF,GOAL_THREAT,Goal Threat,Production Style,84.3,True,0.575299,Medium,Stable,Provisional,605,9,"{""window_weights"":{""earlier_current"":0.0,""prev...",[],0.0,stable,4.0,1.0.0,NaN,NaN,NaN
19,029cbd40,Malo Gusto,2026-08-18T06:57:49.693935+00:00,DEF,GOAL_THREAT,Goal Threat,Production Style,83.5,True,0.703925,Medium,Stable,Provisional,2030,26,"{""window_weights"":{""earlier_current"":0.0,""prev...",[],0.0,stable,2.0,1.0.0,NaN,NaN,NaN
20,25800dde,Jan Paul van Hecke,2026-08-18T06:57:49.693935+00:00,DEF,GOAL_THREAT,Goal Threat,Production Style,81.2,True,0.537865,Low,Stable,Provisional,3210,36,"{""window_weights"":{""earlier_current"":0.0,""prev...",[],0.0,stable,4.0,1.0.0,NaN,NaN,NaN
21,8036342c,Sven Botman,2026-08-18T06:57:49.693935+00:00,DEF,GOAL_THREAT,Goal Threat,Production Style,81.1,True,0.700349,Medium,Stable,Provisional,1819,22,"{""window_weights"":{""earlier_current"":0.0,""prev...",[],0.0,stable,4.0,1.0.0,NaN,NaN,NaN
22,206a1d8a,Nathan Collins,2026-08-18T06:57:49.693935+00:00,DEF,GOAL_THREAT,Goal Threat,Production Style,80.3,True,0.714980,Medium,Stable,Provisional,2955,34,"{""window_weights"":{""earlier_current"":0.0,""prev...",[],0.0,stable,4.0,1.0.0,NaN,NaN,NaN
23,1ea0d01b,James Tarkowski,2026-08-18T06:57:49.693935+00:00,DEF,GOAL_THREAT,Goal Threat,Production Style,79.5,True,0.718085,Medium,Stable,Established,3330,37,"{""window_weights"":{""earlier_current"":0.0,""prev...",[],0.0,stable,4.0,1.0.0,NaN,NaN,NaN
24,a4b06ce2,Sepp van den Berg,2026-08-18T06:57:49.693935+00:00,DEF,GOAL_THREAT,Goal Threat,Production Style,76.4,True,0.713044,Medium,Stable,Established,2753,31,"{""window_weights"":{""earlier_current"":0.0,""prev...",[],0.0,stable,4.0,1.0.0,NaN,NaN,NaN

'Defenders - DEFENSIVE_ENGINE score:'

,player_id,player_name,snapshot_date,fpl_position,archetype_id,display_name,family,score_0_100,active_label,confidence_0_1,confidence_band,trend,status,evidence_minutes,eligible_appearances,component_scores,missing_data_flags,below_exit_updates,trend_direction,trend_persistence,model_version,pending_usage_state,pending_usage_updates,transition_applied
0,3d3aac52,Chris Richards,2026-08-18T06:57:49.693935+00:00,DEF,DEFENSIVE_ENGINE,Defensive Engine,Production Style,98.40,True,0.713336,Medium,Stable,Provisional,2782,31,"{""window_weights"":{""earlier_current"":0.0,""prev...",[],0.0,stable,4.0,1.0.0,NaN,NaN,NaN
1,4c1986a4,Jaydee Canvot,2026-08-18T06:57:49.693935+00:00,DEF,DEFENSIVE_ENGINE,Defensive Engine,Production Style,97.70,True,0.688859,Medium,Stable,Provisional,1308,16,"{""window_weights"":{""earlier_current"":0.0,""prev...",[],0.0,stable,4.0,1.0.0,NaN,NaN,NaN
2,c5fc8a09,Kevin Danso,2026-08-18T06:57:49.693935+00:00,DEF,DEFENSIVE_ENGINE,Defensive Engine,Production Style,96.90,True,0.692333,Medium,Stable,Provisional,1441,17,"{""window_weights"":{""earlier_current"":0.0,""prev...",[],0.0,stable,4.0,1.0.0,NaN,NaN,NaN
3,3213dc02,James Justin,2026-08-18T06:57:49.693935+00:00,DEF,DEFENSIVE_ENGINE,Defensive Engine,Production Style,96.10,True,0.700874,Medium,Stable,Provisional,1848,22,"{""window_weights"":{""earlier_current"":0.0,""prev...",[],0.0,stable,4.0,1.0.0,NaN,NaN,NaN
4,15b06139,Nordi Mukiele,2026-08-18T06:57:49.693935+00:00,DEF,DEFENSIVE_ENGINE,Defensive Engine,Production Style,95.30,True,0.713245,Medium,Stable,Provisional,2773,31,"{""window_weights"":{""earlier_current"":0.0,""prev...",[],0.0,stable,4.0,1.0.0,NaN,NaN,NaN
5,67627fa9,Antonee Robinson,2026-08-18T06:57:49.693935+00:00,DEF,DEFENSIVE_ENGINE,Defensive Engine,Production Style,94.60,True,0.691507,Medium,Stable,Provisional,1408,17,"{""window_weights"":{""earlier_current"":0.0,""prev...",[],0.0,stable,4.0,1.0.0,NaN,NaN,NaN
6,322d5e0f,Daniel Muñoz,2026-08-18T06:57:49.693935+00:00,DEF,DEFENSIVE_ENGINE,Defensive Engine,Production Style,93.80,True,0.708929,Medium,Stable,Provisional,2387,28,"{""window_weights"":{""earlier_current"":0.0,""prev...",[],0.0,stable,4.0,1.0.0,NaN,NaN,NaN
7,4b2c14b1,Murillo,2026-08-18T06:57:49.693935+00:00,DEF,DEFENSIVE_ENGINE,Defensive Engine,Production Style,93.00,True,0.705446,Medium,Stable,Provisional,2130,25,"{""window_weights"":{""earlier_current"":0.0,""prev...",[],0.0,stable,4.0,1.0.0,NaN,NaN,NaN
8,c6810ee5,Adrien Truffert,2026-08-18T06:57:49.693935+00:00,DEF,DEFENSIVE_ENGINE,Defensive Engine,Production Style,92.20,True,0.718443,Medium,Stable,Provisional,3378,38,"{""window_weights"":{""earlier_current"":0.0,""prev...",[],0.0,stable,4.0,1.0.0,NaN,NaN,NaN
9,d50caf0b,Jorge Cuenca,2026-08-18T06:57:49.693935+00:00,DEF,DEFENSIVE_ENGINE,Defensive Engine,Production Style,91.50,True,0.675987,Medium,Stable,Provisional,924,11,"{""window_weights"":{""earlier_current"":0.0,""prev...",[],0.0,stable,4.0,1.0.0,NaN,NaN,NaN
10,20f73533,Cristian Romero,2026-08-18T06:57:49.693935+00:00,DEF,DEFENSIVE_ENGINE,Defensive Engine,Production Style,90.70,True,0.699076,Medium,Stable,Provisional,1751,21,"{""window_weights"":{""earlier_current"":0.0,""prev...",[],0.0,stable,4.0,1.0.0,NaN,NaN,NaN
11,3aa7d48a,Maxence Lacroix,2026-08-18T06:57:49.693935+00:00,DEF,DEFENSIVE_ENGINE,Defensive Engine,Production Style,90.00,True,0.536736,Low,Stable,Provisional,3030,34,"{""window_weights"":{""earlier_current"":0.0,""prev...",[],0.0,stable,4.0,1.0.0,NaN,NaN,NaN
12,d5dea5d7,James Hill,2026-08-18T06:57:49.693935+00:00,DEF,DEFENSIVE_ENGINE,Defensive Engine,Production Style,89.90,True,0.704314,Medium,Stable,Provisional,2055,24,"{""window_weights"":{""earlier_current"":0.0,""prev...",[],0.0,stable,4.0,1.0.0,NaN,NaN,NaN
13,7edccf6c,Marcos Senesi,2026-08-18T06:57:49.693935+00:00,DEF,DEFENSIVE_ENGINE,Defensive Engine,Production Style,89.36,True,0.538324,Low,Stable,Provisional,3288,37,"{""window_weights"":{""earlier_current"":0.0,""prev...",[],0.0,stable,4.0,1.0.0,NaN,NaN,NaN
14,bef4a612,Mats Wieffer,2026-08-18T06:57:49.693935+00:00,DEF,DEFENSIVE_ENGINE,Defensive Engine,Production Style,89.10,True,0.561137,Medium,Stable,Provisional,1879,24,"{""window_weights"":{""earlier_current"":0.0,""prev...",[],0.0,stable,4.0,1.0.0,NaN,NaN,NaN
15,28656e7a,Jaka Bijol,2026-08-18T06:57:49.693935+00:00,DEF,DEFENSIVE_ENGINE,Defensive Engine,Production Style,88.40,True,0.701421,Medium,Stable,Provisional,1879,23,"{""window_weights"":{""earlier_current"":0.0,""prev...",[],0.0,stable,4.0,1.0.0,NaN,NaN,NaN
16,58cd090c,Tyrick Mitchell,2026-08-18T06:57:49.693935+00:00,DEF,DEFENSIVE_ENGINE,Defensive Engine,Production Style,87.60,True,0.717494,Medium,Stable,Provisional,3253,38,"{""window_weights"":{""earlier_current"":0.0,""prev...",[],0.0,stable,4.0,1.0.0,NaN,NaN,NaN
17,86bafbee,Piero Hincapié,2026-08-18T06:57:49.693935+00:00,DEF,DEFENSIVE_ENGINE,Defensive Engine,Production Style,86.80,True,0.698157,Medium,Stable,Provisional,1704,20,"{""window_weights"":{""earlier_current"":0.0,""prev...",[],0.0,stable,4.0,1.0.0,NaN,NaN,NaN
18,97395184,Wesley Fofana,2026-08-18T06:57:49.693935+00:00,DEF,DEFENSIVE_ENGINE,Defensive Engine,Production Style,85.30,True,0.694604,Medium,Stable,Provisional,1537,20,"{""window_weights"":{""earlier_current"":0.0,""prev...",[],0.0,stable,4.0,1.0.0,NaN,NaN,NaN
19,6eb98627,Joachim Andersen,2026-08-18T06:57:49.693935+00:00,DEF,DEFENSIVE_ENGINE,Defensive Engine,Production Style,84.50,True,0.713817,Medium,Stable,Provisional,2831,32,"{""window_weights"":{""earlier_current"":0.0,""prev...",[],0.0,stable,4.0,1.0.0,NaN,NaN,NaN
20,09f73256,Michael Keane,2026-08-18T06:57:49.693935+00:00,DEF,DEFENSIVE_ENGINE,Defensive Engine,Production Style,83.70,True,0.710224,Medium,Stable,Provisional,2494,28,"{""window_weights"":{""earlier_current"":0.0,""prev...",[],0.0,stable,4.0,1.0.0,NaN,NaN,NaN
21,6a10e512,Kenny Tete,2026-08-18T06:57:49.693935+00:00,DEF,DEFENSIVE_ENGINE,Defensive Engine,Production Style,82.90,True,0.699702,Medium,Stable,Provisional,1784,21,"{""window_weights"":{""earlier_current"":0.0,""prev...",[],0.0,stable,4.0,1.0.0,NaN,NaN,NaN
22,8036342c,Sven Botman,2026-08-18T06:57:49.693935+00:00,DEF,DEFENSIVE_ENGINE,Defensive Engine,Production Style,82.20,True,0.700349,Medium,Stable,Provisional,1819,22,"{""window_weights"":{""earlier_current"":0.0,""prev...",[],0.0,stable,4.0,1.0.0,NaN,NaN,NaN
23,0db121d1,Pedro Porro,2026-08-18T06:57:49.693935+00:00,DEF,DEFENSIVE_ENGINE,Defensive Engine,Production Style,81.40,True,0.713054,Medium,Stable,Provisional,2754,32,"{""window_weights"":{""earlier_current"":0.0,""prev...",[],0.0,stable,4.0,1.0.0,NaN,NaN,NaN
24,1ea0d01b,James Tarkowski,2026-08-18T06:57:49.693935+00:00,DEF,DEFENSIVE_ENGINE,Defensive Engine,Production Style,80.60,True,0.718085,Medium,Stable,Provisional,3330,37,"{""window_weights"":{""earlier_current"":0.0,""prev...",[],0.0,stable,4.0,1.0.0,NaN,NaN,NaN

'Forwards - GOAL_THREAT score:'

,player_id,player_name,snapshot_date,fpl_position,archetype_id,display_name,family,score_0_100,active_label,confidence_0_1,confidence_band,trend,status,evidence_minutes,eligible_appearances,component_scores,missing_data_flags,below_exit_updates,trend_direction,trend_persistence,model_version,pending_usage_state,pending_usage_updates,transition_applied
0,716dbae5,Erling Haaland,2026-08-18T06:57:49.693935+00:00,FWD,GOAL_THREAT,Goal Threat,Production Style,100.0,True,0.714807,Medium,Stable,Provisional,2936,34,"{""window_weights"":{""earlier_current"":0.0,""prev...",[],0.0,stable,4.0,1.0.0,NaN,NaN,NaN
1,b582a652,Benjamin Šeško,2026-08-18T06:57:49.693935+00:00,FWD,GOAL_THREAT,Goal Threat,Production Style,97.5,True,0.692357,Medium,Stable,Provisional,1442,20,"{""window_weights"":{""earlier_current"":0.0,""prev...",[],0.0,stable,4.0,1.0.0,NaN,NaN,NaN
2,11c3c63c,Thiago,2026-08-18T06:57:49.693935+00:00,FWD,GOAL_THREAT,Goal Threat,Production Style,95.0,True,0.717718,Medium,Stable,Provisional,3282,38,"{""window_weights"":{""earlier_current"":0.0,""prev...",[],0.0,stable,4.0,1.0.0,NaN,NaN,NaN
3,d84f96dc,Ollie Watkins,2026-08-18T06:57:49.693935+00:00,FWD,GOAL_THREAT,Goal Threat,Production Style,92.5,True,0.713553,Medium,Stable,Provisional,2804,36,"{""window_weights"":{""earlier_current"":0.0,""prev...",[],0.0,stable,4.0,1.0.0,NaN,NaN,NaN
4,3e0efa55,Hugo Ekitike,2026-08-18T06:57:49.693935+00:00,FWD,GOAL_THREAT,Goal Threat,Production Style,90.0,True,0.697715,Medium,Stable,Provisional,1682,22,"{""window_weights"":{""earlier_current"":0.0,""prev...",[],0.0,stable,4.0,1.0.0,NaN,NaN,NaN
5,fd6894bf,Dominic Calvert-Lewin,2026-08-18T06:57:49.693935+00:00,FWD,GOAL_THREAT,Goal Threat,Production Style,87.5,True,0.711929,Medium,Stable,Provisional,2646,31,"{""window_weights"":{""earlier_current"":0.0,""prev...",[],0.0,stable,4.0,1.0.0,NaN,NaN,NaN
6,6ad571e3,Beto,2026-08-18T06:57:49.693935+00:00,FWD,GOAL_THREAT,Goal Threat,Production Style,85.0,True,0.689624,Medium,Stable,Provisional,1336,20,"{""window_weights"":{""earlier_current"":0.0,""prev...",[],0.0,stable,4.0,1.0.0,NaN,NaN,NaN
7,e8220773,Kai Havertz,2026-08-18T06:57:49.693935+00:00,FWD,GOAL_THREAT,Goal Threat,Production Style,82.5,True,0.566250,Medium,Stable,Provisional,540,10,"{""window_weights"":{""earlier_current"":0.0,""prev...",[],0.0,stable,4.0,1.0.0,NaN,NaN,NaN

'Forwards - DEFENSIVE_ENGINE score:'

,player_id,player_name,snapshot_date,fpl_position,archetype_id,display_name,family,score_0_100,active_label,confidence_0_1,confidence_band,trend,status,evidence_minutes,eligible_appearances,component_scores,missing_data_flags,below_exit_updates,trend_direction,trend_persistence,model_version,pending_usage_state,pending_usage_updates,transition_applied
0,11c3c63c,Thiago,2026-08-18T06:57:49.693935+00:00,FWD,DEFENSIVE_ENGINE,Defensive Engine,Production Style,100.0,True,0.717718,Medium,Stable,Provisional,3282,38,"{""window_weights"":{""earlier_current"":0.0,""prev...",[],0.0,stable,4.0,1.0.0,NaN,NaN,NaN
1,770032c1,Georginio Rutter,2026-08-18T06:57:49.693935+00:00,FWD,DEFENSIVE_ENGINE,Defensive Engine,Production Style,97.5,True,0.556817,Medium,Stable,Provisional,1601,21,"{""window_weights"":{""earlier_current"":0.0,""prev...",[],0.0,stable,4.0,1.0.0,NaN,NaN,NaN
2,f49f1724,Richarlison,2026-08-18T06:57:49.693935+00:00,FWD,DEFENSIVE_ENGINE,Defensive Engine,Production Style,92.5,True,0.700129,Medium,Stable,Provisional,1807,24,"{""window_weights"":{""earlier_current"":0.0,""prev...",[],0.0,stable,4.0,1.0.0,NaN,NaN,NaN
3,3bf91065,Lukas Nmecha,2026-08-18T06:57:49.693935+00:00,FWD,DEFENSIVE_ENGINE,Defensive Engine,Production Style,87.5,True,0.637855,Medium,Stable,Provisional,774,12,"{""window_weights"":{""earlier_current"":0.0,""prev...",[],0.0,stable,4.0,1.0.0,NaN,NaN,NaN
4,d8435afe,Dominic Solanke,2026-08-18T06:57:49.693935+00:00,FWD,DEFENSIVE_ENGINE,Defensive Engine,Production Style,85.0,True,0.675414,Medium,Stable,Provisional,910,11,"{""window_weights"":{""earlier_current"":0.0,""prev...",[],0.0,stable,4.0,1.0.0,NaN,NaN,NaN
5,9ba7a3af,João Pedro,2026-08-18T06:57:49.693935+00:00,FWD,DEFENSIVE_ENGINE,Defensive Engine,Production Style,82.5,True,0.711604,Medium,Stable,Provisional,2616,33,"{""window_weights"":{""earlier_current"":0.0,""prev...",[],0.0,stable,4.0,1.0.0,NaN,NaN,NaN
6,d851d07b,Danny Welbeck,2026-08-18T06:57:49.693935+00:00,FWD,DEFENSIVE_ENGINE,Defensive Engine,Production Style,82.0,True,0.528352,Low,Stable,Provisional,2065,26,"{""window_weights"":{""earlier_current"":0.0,""prev...",[],0.0,stable,4.0,1.0.0,NaN,NaN,NaN

In [61]:
players_2025 = pd.read_csv("../data/processed/whoscored/ENG-Premier League/2025-2026/player_match/defense.csv", usecols=('provider_match_id', 'player', 'player_id', 'provider_position_match'))

players_2024 = pd.read_csv("../data/processed/whoscored/ENG-Premier League/2024-2025/player_match/defense.csv", usecols=('provider_match_id', 'player', 'player_id', 'provider_position_match'))

players_2023 = pd.read_csv("../data/processed/whoscored/ENG-Premier League/2023-2024/player_match/defense.csv", usecols=('provider_match_id', 'player', 'player_id', 'provider_position_match'))

merged = pd.concat(players_2025, players_2024)
#merged = pd.merge(merged, players_2023, how='left', on='player_id')
print(merged.columns)
#timber = merged[merged['player_id'].eq('8be75f47')]
#print(timber['provider_position_match'].value_counts())

TypeError: concat() takes 1 positional argument but 2 were given

In [ ]:
from pathlib import Path
import pandas as pd

data_dir = Path("../data/processed/whoscored/ENG-Premier League")
cols = [
    "provider_match_id",
    "player",
    "player_id",
    "provider_position_match",
]

players = pd.concat(
    [
        pd.read_csv(data_dir / season / "player_match/defense.csv", usecols=cols)
        .assign(season=season)
        for season in ["2025-2026", "2024-2025", "2023-2024"]
    ],
    ignore_index=True,
)

timber = players.loc[players["player_id"].eq("8be75f47")]
pos =

print(
    timber["provider_position_match"]
    .value_counts()
)
print(
    timber["provider_position_match"]
    .count()
)

provider_position_match
DR     44
DL      9
Sub     8
DC      3
Name: count, dtype: int64
64